ALL_CAS_CODES = {
    "47": {
        "nombre": "Envío datos liquidación..." if len("Envío datos liquidación") > 60 else "Envío datos liquidación",
        "descripcion": "Envío datos liquidación",
        "emisor": "HOSPITAL",
        "tipo": "INICIO",
    },
    "101": {
        "nombre": "PA Urgencias..." if len("PA Urgencias") > 60 else "PA Urgencias",
        "descripcion": "PA Urgencias",
        "emisor": "HOSPITAL",
        "tipo": "INICIO",
    },
    "102": {
        "nombre": "PA urgencias modificado..." if len("PA urgencias modificado") > 60 else "PA urgencias modificado",
        "descripcion": "PA urgencias modificado",
        "emisor": "HOSPITAL",
        "tipo": "INICIO",
    },
    "170": {
        "nombre": "Parte de comunicación de lesiones..." if len("Parte de comunicación de lesiones") > 60 else "Parte de comunicación de lesiones",
        "descripcion": "Parte de comunicación de lesiones",
        "emisor": "SISTEMA",
        "tipo": "INICIO",
    },
    "171": {
        "nombre": "Envío parte de asistencia / Parte de primera Asistencia ambu..." if len("Envío parte de asistencia / Parte de primera Asistencia ambulatoria u hospitalaria. (descripción que aplica al convenio 2010T y 2010U)") > 60 else "Envío parte de asistencia / Parte de primera Asistencia ambulatoria u hospitalaria. (descripción que aplica al convenio 2010T y 2010U)",
        "descripcion": "Envío parte de asistencia / Parte de primera Asistencia ambulatoria u hospitalaria. (descripción que aplica al convenio 2010T y 2010U)",
        "emisor": "HOSPITAL",
        "tipo": "INICIO",
    },
    "172": {
        "nombre": "Envío nuevo parte de asistencia modificado / PA ambulatorio ..." if len("Envío nuevo parte de asistencia modificado / PA ambulatorio modificado (descripción que aplica al convenio 2010T y 2010U)") > 60 else "Envío nuevo parte de asistencia modificado / PA ambulatorio modificado (descripción que aplica al convenio 2010T y 2010U)",
        "descripcion": "Envío nuevo parte de asistencia modificado / PA ambulatorio modificado (descripción que aplica al convenio 2010T y 2010U)",
        "emisor": "HOSPITAL",
        "tipo": "INICIO",
    },
    "173": {
        "nombre": "Envía parte de asistencia de reingreso. / PA reingreso/PA co..." if len("Envía parte de asistencia de reingreso. / PA reingreso/PA continuación gestión lesionado. (descripción que aplica al convenio 2010T y 2010U)") > 60 else "Envía parte de asistencia de reingreso. / PA reingreso/PA continuación gestión lesionado. (descripción que aplica al convenio 2010T y 2010U)",
        "descripcion": "Envía parte de asistencia de reingreso. / PA reingreso/PA continuación gestión lesionado. (descripción que aplica al convenio 2010T y 2010U)",
        "emisor": "HOSPITAL",
        "tipo": "INICIO",
    },
    "174": {
        "nombre": "Envía parte de asistencia de reingreso modificado...." if len("Envía parte de asistencia de reingreso modificado.") > 60 else "Envía parte de asistencia de reingreso modificado.",
        "descripcion": "Envía parte de asistencia de reingreso modificado.",
        "emisor": "HOSPITAL",
        "tipo": "INICIO",
    },
    "175": {
        "nombre": "Envío parte de asistencia informativo..." if len("Envío parte de asistencia informativo") > 60 else "Envío parte de asistencia informativo",
        "descripcion": "Envío parte de asistencia informativo",
        "emisor": "HOSPITAL",
        "tipo": "INICIO",
    },
    "176": {
        "nombre": "Envío parte de asistencia de entidad no adherida a convenio..." if len("Envío parte de asistencia de entidad no adherida a convenio") > 60 else "Envío parte de asistencia de entidad no adherida a convenio",
        "descripcion": "Envío parte de asistencia de entidad no adherida a convenio",
        "emisor": "HOSPITAL",
        "tipo": "INICIO",
    },
    "181": {
        "nombre": "Envío factura...." if len("Envío factura.") > 60 else "Envío factura.",
        "descripcion": "Envío factura.",
        "emisor": "HOSPITAL",
        "tipo": "INICIO",
    },
    "191": {
        "nombre": "Envío parte de traslado interhospitalario...." if len("Envío parte de traslado interhospitalario.") > 60 else "Envío parte de traslado interhospitalario.",
        "descripcion": "Envío parte de traslado interhospitalario.",
        "emisor": "HOSPITAL",
        "tipo": "INICIO",
    },
    "192": {
        "nombre": "Envío nuevo parte de traslado interhospitalario modificado..." if len("Envío nuevo parte de traslado interhospitalario modificado") > 60 else "Envío nuevo parte de traslado interhospitalario modificado",
        "descripcion": "Envío nuevo parte de traslado interhospitalario modificado",
        "emisor": "HOSPITAL",
        "tipo": "INICIO",
    },
    "201": {
        "nombre": "Acepta parte de urgencias..." if len("Acepta parte de urgencias") > 60 else "Acepta parte de urgencias",
        "descripcion": "Acepta parte de urgencias",
        "emisor": "ASEGURADORA",
        "tipo": "RESPUESTA",
    },
    "202": {
        "nombre": "Acepta continuación tratamiento..." if len("Acepta continuación tratamiento") > 60 else "Acepta continuación tratamiento",
        "descripcion": "Acepta continuación tratamiento",
        "emisor": "ASEGURADORA",
        "tipo": "RESPUESTA",
    },
    "203": {
        "nombre": "Acepta lesionado alta especialización..." if len("Acepta lesionado alta especialización") > 60 else "Acepta lesionado alta especialización",
        "descripcion": "Acepta lesionado alta especialización",
        "emisor": "ASEGURADORA",
        "tipo": "RESPUESTA",
    },
    "270": {
        "nombre": "Subcomisión acepta parte..." if len("Subcomisión acepta parte") > 60 else "Subcomisión acepta parte",
        "descripcion": "Subcomisión acepta parte",
        "emisor": "SISTEMA",
        "tipo": "RESPUESTA",
    },
    "271": {
        "nombre": "Acepta el parte de asistencia...." if len("Acepta el parte de asistencia.") > 60 else "Acepta el parte de asistencia.",
        "descripcion": "Acepta el parte de asistencia.",
        "emisor": "ASEGURADORA",
        "tipo": "RESPUESTA",
    },
    "272": {
        "nombre": "Comisión acepta parte..." if len("Comisión acepta parte") > 60 else "Comisión acepta parte",
        "descripcion": "Comisión acepta parte",
        "emisor": "SISTEMA",
        "tipo": "RESPUESTA",
    },
    "275": {
        "nombre": "Subcomision acepta parte tras recurso..." if len("Subcomision acepta parte tras recurso") > 60 else "Subcomision acepta parte tras recurso",
        "descripcion": "Subcomision acepta parte tras recurso",
        "emisor": "SISTEMA",
        "tipo": "RESPUESTA",
    },
    "280": {
        "nombre": "Subcomisión acepta factura..." if len("Subcomisión acepta factura") > 60 else "Subcomisión acepta factura",
        "descripcion": "Subcomisión acepta factura",
        "emisor": "SISTEMA",
        "tipo": "RESPUESTA",
    },
    "281": {
        "nombre": "Acepta la factura...." if len("Acepta la factura.") > 60 else "Acepta la factura.",
        "descripcion": "Acepta la factura.",
        "emisor": "ASEGURADORA",
        "tipo": "RESPUESTA",
    },
    "284": {
        "nombre": "Comisión acepta factura..." if len("Comisión acepta factura") > 60 else "Comisión acepta factura",
        "descripcion": "Comisión acepta factura",
        "emisor": "SISTEMA",
        "tipo": "RESPUESTA",
    },
    "285": {
        "nombre": "Comisión acepta pago..." if len("Comisión acepta pago") > 60 else "Comisión acepta pago",
        "descripcion": "Comisión acepta pago",
        "emisor": "SISTEMA",
        "tipo": "RESPUESTA",
    },
    "287": {
        "nombre": "Subcomisión acepta pago total..." if len("Subcomisión acepta pago total") > 60 else "Subcomisión acepta pago total",
        "descripcion": "Subcomisión acepta pago total",
        "emisor": "SISTEMA",
        "tipo": "RESPUESTA",
    },
    "288": {
        "nombre": "Subcomisión acepta factura tras recurso..." if len("Subcomisión acepta factura tras recurso") > 60 else "Subcomisión acepta factura tras recurso",
        "descripcion": "Subcomisión acepta factura tras recurso",
        "emisor": "SISTEMA",
        "tipo": "RESPUESTA",
    },
    "301": {
        "nombre": "Comunica Continuación tratamiento..." if len("Comunica Continuación tratamiento") > 60 else "Comunica Continuación tratamiento",
        "descripcion": "Comunica Continuación tratamiento",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "302": {
        "nombre": "Comunica cambio de diagnóstico..." if len("Comunica cambio de diagnóstico") > 60 else "Comunica cambio de diagnóstico",
        "descripcion": "Comunica cambio de diagnóstico",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "303": {
        "nombre": "Acepta cambio de diagnóstico..." if len("Acepta cambio de diagnóstico") > 60 else "Acepta cambio de diagnóstico",
        "descripcion": "Acepta cambio de diagnóstico",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "304": {
        "nombre": "Rechaza cambio de diagnóstico..." if len("Rechaza cambio de diagnóstico") > 60 else "Rechaza cambio de diagnóstico",
        "descripcion": "Rechaza cambio de diagnóstico",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "305": {
        "nombre": "Solicita aclaraciones cambio de diagnóstico..." if len("Solicita aclaraciones cambio de diagnóstico") > 60 else "Solicita aclaraciones cambio de diagnóstico",
        "descripcion": "Solicita aclaraciones cambio de diagnóstico",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "306": {
        "nombre": "Envía aclaraciones cambio diagnóstico..." if len("Envía aclaraciones cambio diagnóstico") > 60 else "Envía aclaraciones cambio diagnóstico",
        "descripcion": "Envía aclaraciones cambio diagnóstico",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "308": {
        "nombre": "Acepta rechazo de factura..." if len("Acepta rechazo de factura") > 60 else "Acepta rechazo de factura",
        "descripcion": "Acepta rechazo de factura",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "309": {
        "nombre": "No acepta rechazo de factura..." if len("No acepta rechazo de factura") > 60 else "No acepta rechazo de factura",
        "descripcion": "No acepta rechazo de factura",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "310": {
        "nombre": "Vencido plazo subcomisión..." if len("Vencido plazo subcomisión") > 60 else "Vencido plazo subcomisión",
        "descripcion": "Vencido plazo subcomisión",
        "emisor": "SISTEMA",
        "tipo": "DOCUMENTACION",
    },
    "311": {
        "nombre": "Solicita informe médico de evolución..." if len("Solicita informe médico de evolución") > 60 else "Solicita informe médico de evolución",
        "descripcion": "Solicita informe médico de evolución",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "312": {
        "nombre": "Pendiente Informe de alta de urgencias..." if len("Pendiente Informe de alta de urgencias") > 60 else "Pendiente Informe de alta de urgencias",
        "descripcion": "Pendiente Informe de alta de urgencias",
        "emisor": "SISTEMA",
        "tipo": "DOCUMENTACION",
    },
    "313": {
        "nombre": "Vencido plazo subcomisión factura..." if len("Vencido plazo subcomisión factura") > 60 else "Vencido plazo subcomisión factura",
        "descripcion": "Vencido plazo subcomisión factura",
        "emisor": "SISTEMA",
        "tipo": "DOCUMENTACION",
    },
    "314": {
        "nombre": "Solicita envío hoja de firmas..." if len("Solicita envío hoja de firmas") > 60 else "Solicita envío hoja de firmas",
        "descripcion": "Solicita envío hoja de firmas",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "315": {
        "nombre": "Solicito autorización pruebas diagnósticas..." if len("Solicito autorización pruebas diagnósticas") > 60 else "Solicito autorización pruebas diagnósticas",
        "descripcion": "Solicito autorización pruebas diagnósticas",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "316": {
        "nombre": "Autorizo pruebas diagnósticas..." if len("Autorizo pruebas diagnósticas") > 60 else "Autorizo pruebas diagnósticas",
        "descripcion": "Autorizo pruebas diagnósticas",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "317": {
        "nombre": "No autorizo pruebas diagnósticas..." if len("No autorizo pruebas diagnósticas") > 60 else "No autorizo pruebas diagnósticas",
        "descripcion": "No autorizo pruebas diagnósticas",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "318": {
        "nombre": "Ampliación plazo...." if len("Ampliación plazo.") > 60 else "Ampliación plazo.",
        "descripcion": "Ampliación plazo.",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "319": {
        "nombre": "Acepto Infiltraciones-bloqueos facetarios, nerviosos...." if len("Acepto Infiltraciones-bloqueos facetarios, nerviosos.") > 60 else "Acepto Infiltraciones-bloqueos facetarios, nerviosos.",
        "descripcion": "Acepto Infiltraciones-bloqueos facetarios, nerviosos.",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "320": {
        "nombre": "Rechazo Infiltraciones-bloqueos facetarios, nerviosos...." if len("Rechazo Infiltraciones-bloqueos facetarios, nerviosos.") > 60 else "Rechazo Infiltraciones-bloqueos facetarios, nerviosos.",
        "descripcion": "Rechazo Infiltraciones-bloqueos facetarios, nerviosos.",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "321": {
        "nombre": "Acepto ondas de choque radiales...." if len("Acepto ondas de choque radiales.") > 60 else "Acepto ondas de choque radiales.",
        "descripcion": "Acepto ondas de choque radiales.",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "322": {
        "nombre": "Rechazo ondas de choque radiales...." if len("Rechazo ondas de choque radiales.") > 60 else "Rechazo ondas de choque radiales.",
        "descripcion": "Rechazo ondas de choque radiales.",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "323": {
        "nombre": "Acepto ondas de choque focales...." if len("Acepto ondas de choque focales.") > 60 else "Acepto ondas de choque focales.",
        "descripcion": "Acepto ondas de choque focales.",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "324": {
        "nombre": "Rechazo ondas de choque focales...." if len("Rechazo ondas de choque focales.") > 60 else "Rechazo ondas de choque focales.",
        "descripcion": "Rechazo ondas de choque focales.",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "325": {
        "nombre": "Procede reducción de tarifas..." if len("Procede reducción de tarifas") > 60 else "Procede reducción de tarifas",
        "descripcion": "Procede reducción de tarifas",
        "emisor": "SISTEMA",
        "tipo": "DOCUMENTACION",
    },
    "326": {
        "nombre": "Subcomisión resuelve que procede el cambio de diagnóstico...." if len("Subcomisión resuelve que procede el cambio de diagnóstico.") > 60 else "Subcomisión resuelve que procede el cambio de diagnóstico.",
        "descripcion": "Subcomisión resuelve que procede el cambio de diagnóstico.",
        "emisor": "SISTEMA",
        "tipo": "DOCUMENTACION",
    },
    "327": {
        "nombre": "Subcomisión resuelve que no procede el cambio de diagnóstico..." if len("Subcomisión resuelve que no procede el cambio de diagnóstico.") > 60 else "Subcomisión resuelve que no procede el cambio de diagnóstico.",
        "descripcion": "Subcomisión resuelve que no procede el cambio de diagnóstico.",
        "emisor": "SISTEMA",
        "tipo": "DOCUMENTACION",
    },
    "360": {
        "nombre": "Cambio de referencia del expediente..." if len("Cambio de referencia del expediente") > 60 else "Cambio de referencia del expediente",
        "descripcion": "Cambio de referencia del expediente",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "361": {
        "nombre": "EA solicita módulo reducido..." if len("EA solicita módulo reducido") > 60 else "EA solicita módulo reducido",
        "descripcion": "EA solicita módulo reducido",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "362": {
        "nombre": "Solicita información aclaratoria...." if len("Solicita información aclaratoria.") > 60 else "Solicita información aclaratoria.",
        "descripcion": "Solicita información aclaratoria.",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "363": {
        "nombre": "Envía información aclaratoria...." if len("Envía información aclaratoria.") > 60 else "Envía información aclaratoria.",
        "descripcion": "Envía información aclaratoria.",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "364": {
        "nombre": "CS confirma aplica módulo reducido..." if len("CS confirma aplica módulo reducido") > 60 else "CS confirma aplica módulo reducido",
        "descripcion": "CS confirma aplica módulo reducido",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "365": {
        "nombre": "Justificación de envío fuera de plazo...." if len("Justificación de envío fuera de plazo.") > 60 else "Justificación de envío fuera de plazo.",
        "descripcion": "Justificación de envío fuera de plazo.",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "366": {
        "nombre": "Documentación sin catalogar...." if len("Documentación sin catalogar.") > 60 else "Documentación sin catalogar.",
        "descripcion": "Documentación sin catalogar.",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "367": {
        "nombre": "Documentación sin catalogar..." if len("Documentación sin catalogar") > 60 else "Documentación sin catalogar",
        "descripcion": "Documentación sin catalogar",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "368": {
        "nombre": "Solicita aclaración factura..." if len("Solicita aclaración factura") > 60 else "Solicita aclaración factura",
        "descripcion": "Solicita aclaración factura",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "369": {
        "nombre": "Envía aclaración factura...." if len("Envía aclaración factura.") > 60 else "Envía aclaración factura.",
        "descripcion": "Envía aclaración factura.",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "370": {
        "nombre": "Solicita autorización inicio tratamiento rehabilitador fuera..." if len("Solicita autorización inicio tratamiento rehabilitador fuera termino municipal") > 60 else "Solicita autorización inicio tratamiento rehabilitador fuera termino municipal",
        "descripcion": "Solicita autorización inicio tratamiento rehabilitador fuera termino municipal",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "371": {
        "nombre": "Autoriza tratamiento rehabilitador fuera del término municip..." if len("Autoriza tratamiento rehabilitador fuera del término municipal") > 60 else "Autoriza tratamiento rehabilitador fuera del término municipal",
        "descripcion": "Autoriza tratamiento rehabilitador fuera del término municipal",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "372": {
        "nombre": "No autoriza tratamiento rehabilitador fuera del término muni..." if len("No autoriza tratamiento rehabilitador fuera del término municipal") > 60 else "No autoriza tratamiento rehabilitador fuera del término municipal",
        "descripcion": "No autoriza tratamiento rehabilitador fuera del término municipal",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "373": {
        "nombre": "CS rechaza aplicar módulo reducido..." if len("CS rechaza aplicar módulo reducido") > 60 else "CS rechaza aplicar módulo reducido",
        "descripcion": "CS rechaza aplicar módulo reducido",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "374": {
        "nombre": "Justificante de no aseguramiento...." if len("Justificante de no aseguramiento.") > 60 else "Justificante de no aseguramiento.",
        "descripcion": "Justificante de no aseguramiento.",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "375": {
        "nombre": "Solicita aclaración declaración responsable..." if len("Solicita aclaración declaración responsable") > 60 else "Solicita aclaración declaración responsable",
        "descripcion": "Solicita aclaración declaración responsable",
        "emisor": "SISTEMA",
        "tipo": "DOCUMENTACION",
    },
    "376": {
        "nombre": "Envía aclaración declaración responsable..." if len("Envía aclaración declaración responsable") > 60 else "Envía aclaración declaración responsable",
        "descripcion": "Envía aclaración declaración responsable",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "377": {
        "nombre": "Envía información alegaciones parte..." if len("Envía información alegaciones parte") > 60 else "Envía información alegaciones parte",
        "descripcion": "Envía información alegaciones parte",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "378": {
        "nombre": "Envía información alegaciones parte..." if len("Envía información alegaciones parte") > 60 else "Envía información alegaciones parte",
        "descripcion": "Envía información alegaciones parte",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "379": {
        "nombre": "Envía información alegaciones factura..." if len("Envía información alegaciones factura") > 60 else "Envía información alegaciones factura",
        "descripcion": "Envía información alegaciones factura",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "380": {
        "nombre": "Envía información alegaciones factura..." if len("Envía información alegaciones factura") > 60 else "Envía información alegaciones factura",
        "descripcion": "Envía información alegaciones factura",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "381": {
        "nombre": "Entidad notifica pago de la factura..." if len("Entidad notifica pago de la factura") > 60 else "Entidad notifica pago de la factura",
        "descripcion": "Entidad notifica pago de la factura",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "383": {
        "nombre": "EA diálogo adicional aplicación módulo..." if len("EA diálogo adicional aplicación módulo") > 60 else "EA diálogo adicional aplicación módulo",
        "descripcion": "EA diálogo adicional aplicación módulo",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "384": {
        "nombre": "CS diálogo adicional aplicación módulo..." if len("CS diálogo adicional aplicación módulo") > 60 else "CS diálogo adicional aplicación módulo",
        "descripcion": "CS diálogo adicional aplicación módulo",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "387": {
        "nombre": "EA comunica límite del conductor..." if len("EA comunica límite del conductor") > 60 else "EA comunica límite del conductor",
        "descripcion": "EA comunica límite del conductor",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "390": {
        "nombre": "EA envía aclaraciones Parte Asistencia, solicitud subcomisió..." if len("EA envía aclaraciones Parte Asistencia, solicitud subcomisión") > 60 else "EA envía aclaraciones Parte Asistencia, solicitud subcomisión",
        "descripcion": "EA envía aclaraciones Parte Asistencia, solicitud subcomisión",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "391": {
        "nombre": "CH envía aclaraciones Parte Asistencia, solicitud subcomisió..." if len("CH envía aclaraciones Parte Asistencia, solicitud subcomisión") > 60 else "CH envía aclaraciones Parte Asistencia, solicitud subcomisión",
        "descripcion": "CH envía aclaraciones Parte Asistencia, solicitud subcomisión",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "392": {
        "nombre": "CH envía aclaraciones Parte Asistencia, solicitud Comisión..." if len("CH envía aclaraciones Parte Asistencia, solicitud Comisión") > 60 else "CH envía aclaraciones Parte Asistencia, solicitud Comisión",
        "descripcion": "CH envía aclaraciones Parte Asistencia, solicitud Comisión",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "393": {
        "nombre": "CH envía aclaraciones Factura, solicitud Comisión..." if len("CH envía aclaraciones Factura, solicitud Comisión") > 60 else "CH envía aclaraciones Factura, solicitud Comisión",
        "descripcion": "CH envía aclaraciones Factura, solicitud Comisión",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "394": {
        "nombre": "EA envía aclaraciones Factura, solicitud Comisión..." if len("EA envía aclaraciones Factura, solicitud Comisión") > 60 else "EA envía aclaraciones Factura, solicitud Comisión",
        "descripcion": "EA envía aclaraciones Factura, solicitud Comisión",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "395": {
        "nombre": "CH envía aclaraciones Factura, solicitud Comisión..." if len("CH envía aclaraciones Factura, solicitud Comisión") > 60 else "CH envía aclaraciones Factura, solicitud Comisión",
        "descripcion": "CH envía aclaraciones Factura, solicitud Comisión",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "398": {
        "nombre": "EA envía aclaraciones Parte Asistencia, solicitud Comisión..." if len("EA envía aclaraciones Parte Asistencia, solicitud Comisión") > 60 else "EA envía aclaraciones Parte Asistencia, solicitud Comisión",
        "descripcion": "EA envía aclaraciones Parte Asistencia, solicitud Comisión",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "399": {
        "nombre": "EA envía aclaraciones Factura, solicitud Subcomisión..." if len("EA envía aclaraciones Factura, solicitud Subcomisión") > 60 else "EA envía aclaraciones Factura, solicitud Subcomisión",
        "descripcion": "EA envía aclaraciones Factura, solicitud Subcomisión",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "401": {
        "nombre": "Parte de urgencias no cumplimentado correctamente..." if len("Parte de urgencias no cumplimentado correctamente") > 60 else "Parte de urgencias no cumplimentado correctamente",
        "descripcion": "Parte de urgencias no cumplimentado correctamente",
        "emisor": "ASEGURADORA",
        "tipo": "REHUSE",
    },
    "403": {
        "nombre": "Rechaza lesionado alta especialización..." if len("Rechaza lesionado alta especialización") > 60 else "Rechaza lesionado alta especialización",
        "descripcion": "Rechaza lesionado alta especialización",
        "emisor": "ASEGURADORA",
        "tipo": "REHUSE",
    },
    "421": {
        "nombre": "Rechaza declaración responsable..." if len("Rechaza declaración responsable") > 60 else "Rechaza declaración responsable",
        "descripcion": "Rechaza declaración responsable",
        "emisor": "SISTEMA",
        "tipo": "REHUSE",
    },
    "422": {
        "nombre": "Rechaza parte, transcurrido plazo 72 h. (Traumatismo menor C..." if len("Rechaza parte, transcurrido plazo 72 h. (Traumatismo menor CV)") > 60 else "Rechaza parte, transcurrido plazo 72 h. (Traumatismo menor CV)",
        "descripcion": "Rechaza parte, transcurrido plazo 72 h. (Traumatismo menor CV)",
        "emisor": "ASEGURADORA",
        "tipo": "REHUSE",
    },
    "423": {
        "nombre": "Rechaza parte, lesionado no viaja en espacio destinado a per..." if len("Rechaza parte, lesionado no viaja en espacio destinado a personas") > 60 else "Rechaza parte, lesionado no viaja en espacio destinado a personas",
        "descripcion": "Rechaza parte, lesionado no viaja en espacio destinado a personas",
        "emisor": "ASEGURADORA",
        "tipo": "REHUSE",
    },
    "442": {
        "nombre": "Rechaza factura, transcurrido plazo 72 h. (Traumatismo menor..." if len("Rechaza factura, transcurrido plazo 72 h. (Traumatismo menor CV)") > 60 else "Rechaza factura, transcurrido plazo 72 h. (Traumatismo menor CV)",
        "descripcion": "Rechaza factura, transcurrido plazo 72 h. (Traumatismo menor CV)",
        "emisor": "ASEGURADORA",
        "tipo": "REHUSE",
    },
    "443": {
        "nombre": "Rechaza factura, Lesionado no en espacio destinado a persona..." if len("Rechaza factura, Lesionado no en espacio destinado a personas") > 60 else "Rechaza factura, Lesionado no en espacio destinado a personas",
        "descripcion": "Rechaza factura, Lesionado no en espacio destinado a personas",
        "emisor": "ASEGURADORA",
        "tipo": "REHUSE",
    },
    "471": {
        "nombre": "Rechazo del parte de asistencia...." if len("Rechazo del parte de asistencia.") > 60 else "Rechazo del parte de asistencia.",
        "descripcion": "Rechazo del parte de asistencia.",
        "emisor": "ASEGURADORA",
        "tipo": "REHUSE",
    },
    "472": {
        "nombre": "Parte de asistencia no cumplimentado correctamente...." if len("Parte de asistencia no cumplimentado correctamente.") > 60 else "Parte de asistencia no cumplimentado correctamente.",
        "descripcion": "Parte de asistencia no cumplimentado correctamente.",
        "emisor": "ASEGURADORA",
        "tipo": "REHUSE",
    },
    "473": {
        "nombre": "No hay acuerdo con el contenido del parte de asistencia...." if len("No hay acuerdo con el contenido del parte de asistencia.") > 60 else "No hay acuerdo con el contenido del parte de asistencia.",
        "descripcion": "No hay acuerdo con el contenido del parte de asistencia.",
        "emisor": "ASEGURADORA",
        "tipo": "REHUSE",
    },
    "474": {
        "nombre": "Rechaza el parte por no asegurar al vehículo...." if len("Rechaza el parte por no asegurar al vehículo.") > 60 else "Rechaza el parte por no asegurar al vehículo.",
        "descripcion": "Rechaza el parte por no asegurar al vehículo.",
        "emisor": "ASEGURADORA",
        "tipo": "REHUSE",
    },
    "475": {
        "nombre": "No corresponde el pago (estipulación de Convenio)...." if len("No corresponde el pago (estipulación de Convenio).") > 60 else "No corresponde el pago (estipulación de Convenio).",
        "descripcion": "No corresponde el pago (estipulación de Convenio).",
        "emisor": "ASEGURADORA",
        "tipo": "REHUSE",
    },
    "476": {
        "nombre": "Rechaza parte, no corresponde pago entidad no adherida..." if len("Rechaza parte, no corresponde pago entidad no adherida") > 60 else "Rechaza parte, no corresponde pago entidad no adherida",
        "descripcion": "Rechaza parte, no corresponde pago entidad no adherida",
        "emisor": "ASEGURADORA",
        "tipo": "REHUSE",
    },
    "477": {
        "nombre": "Rechaza parte, conductor sin cobertura..." if len("Rechaza parte, conductor sin cobertura") > 60 else "Rechaza parte, conductor sin cobertura",
        "descripcion": "Rechaza parte, conductor sin cobertura",
        "emisor": "ASEGURADORA",
        "tipo": "REHUSE",
    },
    "478": {
        "nombre": "Rechaza por existir seguro..." if len("Rechaza por existir seguro") > 60 else "Rechaza por existir seguro",
        "descripcion": "Rechaza por existir seguro",
        "emisor": "SISTEMA",
        "tipo": "REHUSE",
    },
    "481": {
        "nombre": "Rechaza factura. / Rechaza factura: asistencia posterior a c..." if len("Rechaza factura. / Rechaza factura: asistencia posterior a comunicación no aceptación (Descripción que aplica al convenio 2010T)") > 60 else "Rechaza factura. / Rechaza factura: asistencia posterior a comunicación no aceptación (Descripción que aplica al convenio 2010T)",
        "descripcion": "Rechaza factura. / Rechaza factura: asistencia posterior a comunicación no aceptación (Descripción que aplica al convenio 2010T)",
        "emisor": "ASEGURADORA",
        "tipo": "REHUSE",
    },
    "482": {
        "nombre": "Rechaza factura por no asegurar el vehículo..." if len("Rechaza factura por no asegurar el vehículo") > 60 else "Rechaza factura por no asegurar el vehículo",
        "descripcion": "Rechaza factura por no asegurar el vehículo",
        "emisor": "ASEGURADORA",
        "tipo": "REHUSE",
    },
    "483": {
        "nombre": "Rechaza factura por no aplicar convenio..." if len("Rechaza factura por no aplicar convenio") > 60 else "Rechaza factura por no aplicar convenio",
        "descripcion": "Rechaza factura por no aplicar convenio",
        "emisor": "ASEGURADORA",
        "tipo": "REHUSE",
    },
    "484": {
        "nombre": "Rechaza factura por existir seguro..." if len("Rechaza factura por existir seguro") > 60 else "Rechaza factura por existir seguro",
        "descripcion": "Rechaza factura por existir seguro",
        "emisor": "SISTEMA",
        "tipo": "REHUSE",
    },
    "485": {
        "nombre": "Rechaza factura, no corresponde pago entidad no adherida..." if len("Rechaza factura, no corresponde pago entidad no adherida") > 60 else "Rechaza factura, no corresponde pago entidad no adherida",
        "descripcion": "Rechaza factura, no corresponde pago entidad no adherida",
        "emisor": "ASEGURADORA",
        "tipo": "REHUSE",
    },
    "486": {
        "nombre": "Rechazo factura, transcurso de los plazos previstos en el Co..." if len("Rechazo factura, transcurso de los plazos previstos en el Convenio") > 60 else "Rechazo factura, transcurso de los plazos previstos en el Convenio",
        "descripcion": "Rechazo factura, transcurso de los plazos previstos en el Convenio",
        "emisor": "ASEGURADORA",
        "tipo": "REHUSE",
    },
    "487": {
        "nombre": "Rechaza Factura, conductor sin cobertura / Rechaza factura: ..." if len("Rechaza Factura, conductor sin cobertura / Rechaza factura: discrepancia o desproporción entre diagnóstico y el tratamiento. (Descripción que aplica al convenio 2010T)") > 60 else "Rechaza Factura, conductor sin cobertura / Rechaza factura: discrepancia o desproporción entre diagnóstico y el tratamiento. (Descripción que aplica al convenio 2010T)",
        "descripcion": "Rechaza Factura, conductor sin cobertura / Rechaza factura: discrepancia o desproporción entre diagnóstico y el tratamiento. (Descripción que aplica al convenio 2010T)",
        "emisor": "ASEGURADORA",
        "tipo": "REHUSE",
    },
    "488": {
        "nombre": "Rechaza factura, prestación no autorizada..." if len("Rechaza factura, prestación no autorizada") > 60 else "Rechaza factura, prestación no autorizada",
        "descripcion": "Rechaza factura, prestación no autorizada",
        "emisor": "ASEGURADORA",
        "tipo": "REHUSE",
    },
    "492": {
        "nombre": "No se trata de un hecho de la circulación...." if len("No se trata de un hecho de la circulación.") > 60 else "No se trata de un hecho de la circulación.",
        "descripcion": "No se trata de un hecho de la circulación.",
        "emisor": "ASEGURADORA",
        "tipo": "REHUSE",
    },
    "494": {
        "nombre": "Transcurso de los plazos previstos en el Convenio...." if len("Transcurso de los plazos previstos en el Convenio.") > 60 else "Transcurso de los plazos previstos en el Convenio.",
        "descripcion": "Transcurso de los plazos previstos en el Convenio.",
        "emisor": "ASEGURADORA",
        "tipo": "REHUSE",
    },
    "495": {
        "nombre": "Existencia probada de fraude...." if len("Existencia probada de fraude.") > 60 else "Existencia probada de fraude.",
        "descripcion": "Existencia probada de fraude.",
        "emisor": "ASEGURADORA",
        "tipo": "REHUSE",
    },
    "496": {
        "nombre": "Falta de relación causal, criterio cronológico...." if len("Falta de relación causal, criterio cronológico.") > 60 else "Falta de relación causal, criterio cronológico.",
        "descripcion": "Falta de relación causal, criterio cronológico.",
        "emisor": "ASEGURADORA",
        "tipo": "REHUSE",
    },
    "497": {
        "nombre": "Falta de relación causal, criterio de intensidad...." if len("Falta de relación causal, criterio de intensidad.") > 60 else "Falta de relación causal, criterio de intensidad.",
        "descripcion": "Falta de relación causal, criterio de intensidad.",
        "emisor": "ASEGURADORA",
        "tipo": "REHUSE",
    },
    "498": {
        "nombre": "Falta de relación causal, criterio topográfico...." if len("Falta de relación causal, criterio topográfico.") > 60 else "Falta de relación causal, criterio topográfico.",
        "descripcion": "Falta de relación causal, criterio topográfico.",
        "emisor": "ASEGURADORA",
        "tipo": "REHUSE",
    },
    "499": {
        "nombre": "Falta de relación causal, criterio de exclusión...." if len("Falta de relación causal, criterio de exclusión.") > 60 else "Falta de relación causal, criterio de exclusión.",
        "descripcion": "Falta de relación causal, criterio de exclusión.",
        "emisor": "ASEGURADORA",
        "tipo": "REHUSE",
    },
    "500": {
        "nombre": "Abandona gestión expediente..." if len("Abandona gestión expediente") > 60 else "Abandona gestión expediente",
        "descripcion": "Abandona gestión expediente",
        "emisor": "HOSPITAL",
        "tipo": "CIERRE",
    },
    "501": {
        "nombre": "Baja de expediente con pago..." if len("Baja de expediente con pago") > 60 else "Baja de expediente con pago",
        "descripcion": "Baja de expediente con pago",
        "emisor": "HOSPITAL",
        "tipo": "CIERRE",
    },
    "502": {
        "nombre": "Baja del expediente..." if len("Baja del expediente") > 60 else "Baja del expediente",
        "descripcion": "Baja del expediente",
        "emisor": "SISTEMA",
        "tipo": "CIERRE",
    },
    "503": {
        "nombre": "Acepta rechazo de parte..." if len("Acepta rechazo de parte") > 60 else "Acepta rechazo de parte",
        "descripcion": "Acepta rechazo de parte",
        "emisor": "SISTEMA",
        "tipo": "CIERRE",
    },
    "504": {
        "nombre": "Baja expediente no convenio...." if len("Baja expediente no convenio.") > 60 else "Baja expediente no convenio.",
        "descripcion": "Baja expediente no convenio.",
        "emisor": "HOSPITAL",
        "tipo": "CIERRE",
    },
    "570": {
        "nombre": "Abandona gestión de factura...." if len("Abandona gestión de factura.") > 60 else "Abandona gestión de factura.",
        "descripcion": "Abandona gestión de factura.",
        "emisor": "SISTEMA",
        "tipo": "CIERRE",
    },
    "572": {
        "nombre": "Subcomisión No procede parte..." if len("Subcomisión No procede parte") > 60 else "Subcomisión No procede parte",
        "descripcion": "Subcomisión No procede parte",
        "emisor": "SISTEMA",
        "tipo": "CIERRE",
    },
    "573": {
        "nombre": "Comisión resuelve: No procede factura / Subcomisión resuelve..." if len("Comisión resuelve: No procede factura / Subcomisión resuelve no procede factura (descripción que aplica al convenio 2010T)") > 60 else "Comisión resuelve: No procede factura / Subcomisión resuelve no procede factura (descripción que aplica al convenio 2010T)",
        "descripcion": "Comisión resuelve: No procede factura / Subcomisión resuelve no procede factura (descripción que aplica al convenio 2010T)",
        "emisor": "SISTEMA",
        "tipo": "CIERRE",
    },
    "574": {
        "nombre": "Subcomisión no procede parte tras recurso / No procede reduc..." if len("Subcomisión no procede parte tras recurso / No procede reducción de tarifas (2010U)") > 60 else "Subcomisión no procede parte tras recurso / No procede reducción de tarifas (2010U)",
        "descripcion": "Subcomisión no procede parte tras recurso / No procede reducción de tarifas (2010U)",
        "emisor": "SISTEMA",
        "tipo": "CIERRE",
    },
    "575": {
        "nombre": "Comisión resuelve no procede parte..." if len("Comisión resuelve no procede parte") > 60 else "Comisión resuelve no procede parte",
        "descripcion": "Comisión resuelve no procede parte",
        "emisor": "SISTEMA",
        "tipo": "CIERRE",
    },
    "576": {
        "nombre": "Comisión resuelve no procede factura..." if len("Comisión resuelve no procede factura") > 60 else "Comisión resuelve no procede factura",
        "descripcion": "Comisión resuelve no procede factura",
        "emisor": "SISTEMA",
        "tipo": "CIERRE",
    },
    "577": {
        "nombre": "Subcomisión no procede factura tras recurso..." if len("Subcomisión no procede factura tras recurso") > 60 else "Subcomisión no procede factura tras recurso",
        "descripcion": "Subcomisión no procede factura tras recurso",
        "emisor": "SISTEMA",
        "tipo": "CIERRE",
    },
    "578": {
        "nombre": "Subcomisión resuelve no procede pago total..." if len("Subcomisión resuelve no procede pago total") > 60 else "Subcomisión resuelve no procede pago total",
        "descripcion": "Subcomisión resuelve no procede pago total",
        "emisor": "SISTEMA",
        "tipo": "CIERRE",
    },
    "579": {
        "nombre": "Comisión resuelve No procede total..." if len("Comisión resuelve No procede total") > 60 else "Comisión resuelve No procede total",
        "descripcion": "Comisión resuelve No procede total",
        "emisor": "SISTEMA",
        "tipo": "CIERRE",
    },
    "580": {
        "nombre": "Envía factura rectificativa de anulación..." if len("Envía factura rectificativa de anulación") > 60 else "Envía factura rectificativa de anulación",
        "descripcion": "Envía factura rectificativa de anulación",
        "emisor": "HOSPITAL",
        "tipo": "FACTURACION",
    },
    "581": {
        "nombre": "Confirma factura abonada totalmente..." if len("Confirma factura abonada totalmente") > 60 else "Confirma factura abonada totalmente",
        "descripcion": "Confirma factura abonada totalmente",
        "emisor": "HOSPITAL",
        "tipo": "FACTURACION",
    },
    "582": {
        "nombre": "Confirma factura abonada parcialmente..." if len("Confirma factura abonada parcialmente") > 60 else "Confirma factura abonada parcialmente",
        "descripcion": "Confirma factura abonada parcialmente",
        "emisor": "HOSPITAL",
        "tipo": "FACTURACION",
    },
    "583": {
        "nombre": "Factura sin abono por Convenio..." if len("Factura sin abono por Convenio") > 60 else "Factura sin abono por Convenio",
        "descripcion": "Factura sin abono por Convenio",
        "emisor": "HOSPITAL",
        "tipo": "FACTURACION",
    },
    "584": {
        "nombre": "Cierre factura. No procede...." if len("Cierre factura. No procede.") > 60 else "Cierre factura. No procede.",
        "descripcion": "Cierre factura. No procede.",
        "emisor": "SISTEMA",
        "tipo": "FACTURACION",
    },
    "585": {
        "nombre": "Envía factura rectificativa de importes..." if len("Envía factura rectificativa de importes") > 60 else "Envía factura rectificativa de importes",
        "descripcion": "Envía factura rectificativa de importes",
        "emisor": "HOSPITAL",
        "tipo": "FACTURACION",
    },
    "586": {
        "nombre": "Cierre factura. No procede total..." if len("Cierre factura. No procede total") > 60 else "Cierre factura. No procede total",
        "descripcion": "Cierre factura. No procede total",
        "emisor": "SISTEMA",
        "tipo": "FACTURACION",
    },
    "587": {
        "nombre": "Cierre factura con embargo..." if len("Cierre factura con embargo") > 60 else "Cierre factura con embargo",
        "descripcion": "Cierre factura con embargo",
        "emisor": "HOSPITAL",
        "tipo": "FACTURACION",
    },
    "652": {
        "nombre": "Alegaciones Subcomisión parte..." if len("Alegaciones Subcomisión parte") > 60 else "Alegaciones Subcomisión parte",
        "descripcion": "Alegaciones Subcomisión parte",
        "emisor": "AMBOS",
        "tipo": "SUBCOMISION",
    },
    "653": {
        "nombre": "Alegaciones Subcomisión factura..." if len("Alegaciones Subcomisión factura") > 60 else "Alegaciones Subcomisión factura",
        "descripcion": "Alegaciones Subcomisión factura",
        "emisor": "AMBOS",
        "tipo": "SUBCOMISION",
    },
    "655": {
        "nombre": "Alegaciones subcomisión cambio de diagnóstico (2010U)..." if len("Alegaciones subcomisión cambio de diagnóstico (2010U)") > 60 else "Alegaciones subcomisión cambio de diagnóstico (2010U)",
        "descripcion": "Alegaciones subcomisión cambio de diagnóstico (2010U)",
        "emisor": "SISTEMA",
        "tipo": "SUBCOMISION",
    },
    "662": {
        "nombre": "Subcomisión automatizada por Parte..." if len("Subcomisión automatizada por Parte") > 60 else "Subcomisión automatizada por Parte",
        "descripcion": "Subcomisión automatizada por Parte",
        "emisor": "SISTEMA",
        "tipo": "SUBCOMISION",
    },
    "663": {
        "nombre": "Subcomisión automatizada por Factura..." if len("Subcomisión automatizada por Factura") > 60 else "Subcomisión automatizada por Factura",
        "descripcion": "Subcomisión automatizada por Factura",
        "emisor": "SISTEMA",
        "tipo": "SUBCOMISION",
    },
    "664": {
        "nombre": "Envío a subcomisión disconformidad reducción tarifa..." if len("Envío a subcomisión disconformidad reducción tarifa") > 60 else "Envío a subcomisión disconformidad reducción tarifa",
        "descripcion": "Envío a subcomisión disconformidad reducción tarifa",
        "emisor": "HOSPITAL",
        "tipo": "SUBCOMISION",
    },
    "665": {
        "nombre": "Subcomision automatizada por cambio de diagnóstico (2010U)..." if len("Subcomision automatizada por cambio de diagnóstico (2010U)") > 60 else "Subcomision automatizada por cambio de diagnóstico (2010U)",
        "descripcion": "Subcomision automatizada por cambio de diagnóstico (2010U)",
        "emisor": "HOSPITAL",
        "tipo": "SUBCOMISION",
    },
    "666": {
        "nombre": "PA elevado a Comisión..." if len("PA elevado a Comisión") > 60 else "PA elevado a Comisión",
        "descripcion": "PA elevado a Comisión",
        "emisor": "SISTEMA",
        "tipo": "SUBCOMISION",
    },
    "667": {
        "nombre": "Factura elevada a Comisión..." if len("Factura elevada a Comisión") > 60 else "Factura elevada a Comisión",
        "descripcion": "Factura elevada a Comisión",
        "emisor": "SISTEMA",
        "tipo": "SUBCOMISION",
    },
    "669": {
        "nombre": "Subcomisión solicita documentación aclaración parte..." if len("Subcomisión solicita documentación aclaración parte") > 60 else "Subcomisión solicita documentación aclaración parte",
        "descripcion": "Subcomisión solicita documentación aclaración parte",
        "emisor": "SISTEMA",
        "tipo": "SUBCOMISION",
    },
    "670": {
        "nombre": "Interlocutores por Parte..." if len("Interlocutores por Parte") > 60 else "Interlocutores por Parte",
        "descripcion": "Interlocutores por Parte",
        "emisor": "AMBOS",
        "tipo": "SUBCOMISION",
    },
    "671": {
        "nombre": "Interlocutores por Factura..." if len("Interlocutores por Factura") > 60 else "Interlocutores por Factura",
        "descripcion": "Interlocutores por Factura",
        "emisor": "AMBOS",
        "tipo": "SUBCOMISION",
    },
    "672": {
        "nombre": "Fin gestión Parte en CAS. Gestionar con subcomisión no autom..." if len("Fin gestión Parte en CAS. Gestionar con subcomisión no automatizada") > 60 else "Fin gestión Parte en CAS. Gestionar con subcomisión no automatizada",
        "descripcion": "Fin gestión Parte en CAS. Gestionar con subcomisión no automatizada",
        "emisor": "SISTEMA",
        "tipo": "SUBCOMISION",
    },
    "673": {
        "nombre": "Fin gestión Factura en CAS. Gestionar con subcomisión no aut..." if len("Fin gestión Factura en CAS. Gestionar con subcomisión no automatizada") > 60 else "Fin gestión Factura en CAS. Gestionar con subcomisión no automatizada",
        "descripcion": "Fin gestión Factura en CAS. Gestionar con subcomisión no automatizada",
        "emisor": "SISTEMA",
        "tipo": "SUBCOMISION",
    },
    "674": {
        "nombre": "Subcomisión por falta de pago..." if len("Subcomisión por falta de pago") > 60 else "Subcomisión por falta de pago",
        "descripcion": "Subcomisión por falta de pago",
        "emisor": "SISTEMA",
        "tipo": "SUBCOMISION",
    },
    "676": {
        "nombre": "CCS Pago pendiente..." if len("CCS Pago pendiente") > 60 else "CCS Pago pendiente",
        "descripcion": "CCS Pago pendiente",
        "emisor": "SISTEMA",
        "tipo": "SUBCOMISION",
    },
    "677": {
        "nombre": "Comisión solicita documentación aclaración Parte..." if len("Comisión solicita documentación aclaración Parte") > 60 else "Comisión solicita documentación aclaración Parte",
        "descripcion": "Comisión solicita documentación aclaración Parte",
        "emisor": "SISTEMA",
        "tipo": "SUBCOMISION",
    },
    "678": {
        "nombre": "Subcomisión solicita documentación aclaración Factura..." if len("Subcomisión solicita documentación aclaración Factura") > 60 else "Subcomisión solicita documentación aclaración Factura",
        "descripcion": "Subcomisión solicita documentación aclaración Factura",
        "emisor": "SISTEMA",
        "tipo": "SUBCOMISION",
    },
    "679": {
        "nombre": "Comisión solicita documentación aclaración Factura..." if len("Comisión solicita documentación aclaración Factura") > 60 else "Comisión solicita documentación aclaración Factura",
        "descripcion": "Comisión solicita documentación aclaración Factura",
        "emisor": "SISTEMA",
        "tipo": "SUBCOMISION",
    },
    "682": {
        "nombre": "Resolución firme subcomisión acepta parte..." if len("Resolución firme subcomisión acepta parte") > 60 else "Resolución firme subcomisión acepta parte",
        "descripcion": "Resolución firme subcomisión acepta parte",
        "emisor": "SISTEMA",
        "tipo": "SUBCOMISION",
    },
    "683": {
        "nombre": "Resolución firme subcomisión no procede parte..." if len("Resolución firme subcomisión no procede parte") > 60 else "Resolución firme subcomisión no procede parte",
        "descripcion": "Resolución firme subcomisión no procede parte",
        "emisor": "SISTEMA",
        "tipo": "SUBCOMISION",
    },
    "684": {
        "nombre": "Resolución firme subcomisión acepta factura..." if len("Resolución firme subcomisión acepta factura") > 60 else "Resolución firme subcomisión acepta factura",
        "descripcion": "Resolución firme subcomisión acepta factura",
        "emisor": "SISTEMA",
        "tipo": "SUBCOMISION",
    },
    "685": {
        "nombre": "Resolución firme subcomisión no procede factura..." if len("Resolución firme subcomisión no procede factura") > 60 else "Resolución firme subcomisión no procede factura",
        "descripcion": "Resolución firme subcomisión no procede factura",
        "emisor": "SISTEMA",
        "tipo": "SUBCOMISION",
    },
    "686": {
        "nombre": "Interlocutores por paciente alta especialización..." if len("Interlocutores por paciente alta especialización") > 60 else "Interlocutores por paciente alta especialización",
        "descripcion": "Interlocutores por paciente alta especialización",
        "emisor": "AMBOS",
        "tipo": "SUBCOMISION",
    },
    "687": {
        "nombre": "Fin gestión lesionado alta complejidad en CAS. Gestionar con..." if len("Fin gestión lesionado alta complejidad en CAS. Gestionar con subcomisión no automatizada") > 60 else "Fin gestión lesionado alta complejidad en CAS. Gestionar con subcomisión no automatizada",
        "descripcion": "Fin gestión lesionado alta complejidad en CAS. Gestionar con subcomisión no automatizada",
        "emisor": "SISTEMA",
        "tipo": "SUBCOMISION",
    },
    "715": {
        "nombre": "Aviso caducidad factura...." if len("Aviso caducidad factura.") > 60 else "Aviso caducidad factura.",
        "descripcion": "Aviso caducidad factura.",
        "emisor": "SISTEMA",
        "tipo": "AVISOS",
    },
    "716": {
        "nombre": "Aviso envío fuera de plazo (15 días naturales) del informe d..." if len("Aviso envío fuera de plazo (15 días naturales) del informe de evolución") > 60 else "Aviso envío fuera de plazo (15 días naturales) del informe de evolución",
        "descripcion": "Aviso envío fuera de plazo (15 días naturales) del informe de evolución",
        "emisor": "SISTEMA",
        "tipo": "AVISOS",
    },
    "717": {
        "nombre": "Aviso presentación de las facturas de las asistencias presta..." if len("Aviso presentación de las facturas de las asistencias prestadas por los CS") > 60 else "Aviso presentación de las facturas de las asistencias prestadas por los CS",
        "descripcion": "Aviso presentación de las facturas de las asistencias prestadas por los CS",
        "emisor": "SISTEMA",
        "tipo": "AVISOS",
    },
    "801": {
        "nombre": "Solicitud de autorización para calificación de lesionado alt..." if len("Solicitud de autorización para calificación de lesionado alta especialización") > 60 else "Solicitud de autorización para calificación de lesionado alta especialización",
        "descripcion": "Solicitud de autorización para calificación de lesionado alta especialización",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "806": {
        "nombre": "Informe cambio diagnóstico..." if len("Informe cambio diagnóstico") > 60 else "Informe cambio diagnóstico",
        "descripcion": "Informe cambio diagnóstico",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "811": {
        "nombre": "Informe médico de evolución..." if len("Informe médico de evolución") > 60 else "Informe médico de evolución",
        "descripcion": "Informe médico de evolución",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "814": {
        "nombre": "Envía documento hoja de firmas..." if len("Envía documento hoja de firmas") > 60 else "Envía documento hoja de firmas",
        "descripcion": "Envía documento hoja de firmas",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "821": {
        "nombre": "Envío declaración de responsable..." if len("Envío declaración de responsable") > 60 else "Envío declaración de responsable",
        "descripcion": "Envío declaración de responsable",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "822": {
        "nombre": "Envío nueva declaración responsable..." if len("Envío nueva declaración responsable") > 60 else "Envío nueva declaración responsable",
        "descripcion": "Envío nueva declaración responsable",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "823": {
        "nombre": "Autorización Infiltraciones-bloqueos facetarios, nerviosos...." if len("Autorización Infiltraciones-bloqueos facetarios, nerviosos.") > 60 else "Autorización Infiltraciones-bloqueos facetarios, nerviosos.",
        "descripcion": "Autorización Infiltraciones-bloqueos facetarios, nerviosos.",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "824": {
        "nombre": "Autorización ondas de choque radiales...." if len("Autorización ondas de choque radiales.") > 60 else "Autorización ondas de choque radiales.",
        "descripcion": "Autorización ondas de choque radiales.",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "825": {
        "nombre": "Autorización ondas de choque focales...." if len("Autorización ondas de choque focales.") > 60 else "Autorización ondas de choque focales.",
        "descripcion": "Autorización ondas de choque focales.",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "841": {
        "nombre": "Justificante de rechazo de parte..." if len("Justificante de rechazo de parte") > 60 else "Justificante de rechazo de parte",
        "descripcion": "Justificante de rechazo de parte",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "861": {
        "nombre": "EA justifica aplicar módulo reducido..." if len("EA justifica aplicar módulo reducido") > 60 else "EA justifica aplicar módulo reducido",
        "descripcion": "EA justifica aplicar módulo reducido",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "863": {
        "nombre": "Envía Documentos originales información aclaratoria...." if len("Envía Documentos originales información aclaratoria.") > 60 else "Envía Documentos originales información aclaratoria.",
        "descripcion": "Envía Documentos originales información aclaratoria.",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "864": {
        "nombre": "Centro sanitario justifica diálogo aplicación módulo reducid..." if len("Centro sanitario justifica diálogo aplicación módulo reducido") > 60 else "Centro sanitario justifica diálogo aplicación módulo reducido",
        "descripcion": "Centro sanitario justifica diálogo aplicación módulo reducido",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "865": {
        "nombre": "Documento original de justificación de envío fuera de plazo...." if len("Documento original de justificación de envío fuera de plazo.") > 60 else "Documento original de justificación de envío fuera de plazo.",
        "descripcion": "Documento original de justificación de envío fuera de plazo.",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "866": {
        "nombre": "Documentación original sin catalogar...." if len("Documentación original sin catalogar.") > 60 else "Documentación original sin catalogar.",
        "descripcion": "Documentación original sin catalogar.",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "867": {
        "nombre": "Documentación original sin catalogar...." if len("Documentación original sin catalogar.") > 60 else "Documentación original sin catalogar.",
        "descripcion": "Documentación original sin catalogar.",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "869": {
        "nombre": "Envía Documentos originales de aclaración factura..." if len("Envía Documentos originales de aclaración factura") > 60 else "Envía Documentos originales de aclaración factura",
        "descripcion": "Envía Documentos originales de aclaración factura",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "870": {
        "nombre": "Documento justificante rechazo factura..." if len("Documento justificante rechazo factura") > 60 else "Documento justificante rechazo factura",
        "descripcion": "Documento justificante rechazo factura",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "874": {
        "nombre": "Documento original de justificante de no aseguramiento...." if len("Documento original de justificante de no aseguramiento.") > 60 else "Documento original de justificante de no aseguramiento.",
        "descripcion": "Documento original de justificante de no aseguramiento.",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "876": {
        "nombre": "Envía doc. original aclaración declaración responsable..." if len("Envía doc. original aclaración declaración responsable") > 60 else "Envía doc. original aclaración declaración responsable",
        "descripcion": "Envía doc. original aclaración declaración responsable",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "877": {
        "nombre": "Doc. original información alegaciones parte..." if len("Doc. original información alegaciones parte") > 60 else "Doc. original información alegaciones parte",
        "descripcion": "Doc. original información alegaciones parte",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "878": {
        "nombre": "Doc. original información alegaciones parte..." if len("Doc. original información alegaciones parte") > 60 else "Doc. original información alegaciones parte",
        "descripcion": "Doc. original información alegaciones parte",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "879": {
        "nombre": "Doc. original información alegaciones factura..." if len("Doc. original información alegaciones factura") > 60 else "Doc. original información alegaciones factura",
        "descripcion": "Doc. original información alegaciones factura",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "880": {
        "nombre": "Doc. original información alegaciones factura..." if len("Doc. original información alegaciones factura") > 60 else "Doc. original información alegaciones factura",
        "descripcion": "Doc. original información alegaciones factura",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "881": {
        "nombre": "Informe de alta de urgencias..." if len("Informe de alta de urgencias") > 60 else "Informe de alta de urgencias",
        "descripcion": "Informe de alta de urgencias",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "885": {
        "nombre": "Envío informe de alta..." if len("Envío informe de alta") > 60 else "Envío informe de alta",
        "descripcion": "Envío informe de alta",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "890": {
        "nombre": "EA envía doc. aclaraciones Parte Asistencia, solicitud subco..." if len("EA envía doc. aclaraciones Parte Asistencia, solicitud subcomisión / Envía documentación solicitud subcomisión (adicional) (descripción que aplica al convenio 2010T)") > 60 else "EA envía doc. aclaraciones Parte Asistencia, solicitud subcomisión / Envía documentación solicitud subcomisión (adicional) (descripción que aplica al convenio 2010T)",
        "descripcion": "EA envía doc. aclaraciones Parte Asistencia, solicitud subcomisión / Envía documentación solicitud subcomisión (adicional) (descripción que aplica al convenio 2010T)",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "891": {
        "nombre": "CH envía doc aclaraciones Parte Asistencia, solicitud subcom..." if len("CH envía doc aclaraciones Parte Asistencia, solicitud subcomisión / Envía documentación solicitud subcomisión (adicional) (descripción que aplica al convenio 2010T)") > 60 else "CH envía doc aclaraciones Parte Asistencia, solicitud subcomisión / Envía documentación solicitud subcomisión (adicional) (descripción que aplica al convenio 2010T)",
        "descripcion": "CH envía doc aclaraciones Parte Asistencia, solicitud subcomisión / Envía documentación solicitud subcomisión (adicional) (descripción que aplica al convenio 2010T)",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "892": {
        "nombre": "CH envía doc. aclaraciones Parte Asistencia, solicitud Comis..." if len("CH envía doc. aclaraciones Parte Asistencia, solicitud Comisión / Envía documentación solicitud comisión (adicional) (descripción que aplica al convenio 2010T)") > 60 else "CH envía doc. aclaraciones Parte Asistencia, solicitud Comisión / Envía documentación solicitud comisión (adicional) (descripción que aplica al convenio 2010T)",
        "descripcion": "CH envía doc. aclaraciones Parte Asistencia, solicitud Comisión / Envía documentación solicitud comisión (adicional) (descripción que aplica al convenio 2010T)",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "893": {
        "nombre": "CH envía doc. aclaraciones Factura, solicitud Comisión / Env..." if len("CH envía doc. aclaraciones Factura, solicitud Comisión / Envía documentación solicitud subcomisión Factura (adicional) (descripción que aplica al convenio 2010T)") > 60 else "CH envía doc. aclaraciones Factura, solicitud Comisión / Envía documentación solicitud subcomisión Factura (adicional) (descripción que aplica al convenio 2010T)",
        "descripcion": "CH envía doc. aclaraciones Factura, solicitud Comisión / Envía documentación solicitud subcomisión Factura (adicional) (descripción que aplica al convenio 2010T)",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "894": {
        "nombre": "EA envía doc. aclaraciones Factura, solicitud Comisión / Env..." if len("EA envía doc. aclaraciones Factura, solicitud Comisión / Envía documentación solicitud comisión Factura (adicional) (descripción que aplica al convenio 2010T)") > 60 else "EA envía doc. aclaraciones Factura, solicitud Comisión / Envía documentación solicitud comisión Factura (adicional) (descripción que aplica al convenio 2010T)",
        "descripcion": "EA envía doc. aclaraciones Factura, solicitud Comisión / Envía documentación solicitud comisión Factura (adicional) (descripción que aplica al convenio 2010T)",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "895": {
        "nombre": "CH envía doc. aclaraciones Factura, solicitud Comisión / Env..." if len("CH envía doc. aclaraciones Factura, solicitud Comisión / Envía documentación solicitud comisión Factura (adicional) ) (descripción que aplica al convenio 2010T)") > 60 else "CH envía doc. aclaraciones Factura, solicitud Comisión / Envía documentación solicitud comisión Factura (adicional) ) (descripción que aplica al convenio 2010T)",
        "descripcion": "CH envía doc. aclaraciones Factura, solicitud Comisión / Envía documentación solicitud comisión Factura (adicional) ) (descripción que aplica al convenio 2010T)",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "896": {
        "nombre": "Documentación subcomisión/comisión..." if len("Documentación subcomisión/comisión") > 60 else "Documentación subcomisión/comisión",
        "descripcion": "Documentación subcomisión/comisión",
        "emisor": "SISTEMA",
        "tipo": "DOCUMENTACION",
    },
    "897": {
        "nombre": "Documentación adicional tras petición subcomisión/comisión..." if len("Documentación adicional tras petición subcomisión/comisión") > 60 else "Documentación adicional tras petición subcomisión/comisión",
        "descripcion": "Documentación adicional tras petición subcomisión/comisión",
        "emisor": "SISTEMA",
        "tipo": "DOCUMENTACION",
    },
    "898": {
        "nombre": "EA envía doc. aclaraciones Parte Asistencia, solicitud Comis..." if len("EA envía doc. aclaraciones Parte Asistencia, solicitud Comisión / Envía documentación solicitud comisión (adicional) (descripción que aplica al convenio 2010T)") > 60 else "EA envía doc. aclaraciones Parte Asistencia, solicitud Comisión / Envía documentación solicitud comisión (adicional) (descripción que aplica al convenio 2010T)",
        "descripcion": "EA envía doc. aclaraciones Parte Asistencia, solicitud Comisión / Envía documentación solicitud comisión (adicional) (descripción que aplica al convenio 2010T)",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "899": {
        "nombre": "EA envía doc. aclaraciones Factura, solicitud Subcomisión / ..." if len("EA envía doc. aclaraciones Factura, solicitud Subcomisión / Envía documentación solicitud subcomisión Factura (adicional) (sólo aplica al convenio 2010T)") > 60 else "EA envía doc. aclaraciones Factura, solicitud Subcomisión / Envía documentación solicitud subcomisión Factura (adicional) (sólo aplica al convenio 2010T)",
        "descripcion": "EA envía doc. aclaraciones Factura, solicitud Subcomisión / Envía documentación solicitud subcomisión Factura (adicional) (sólo aplica al convenio 2010T)",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
}