ALL_CAS_CODES = {
    "101": {
        "nombre": "PA Urgencias..." if len("PA Urgencias") > 50 else "PA Urgencias",
        "descripcion": "PA Urgencias",
        "emisor": "HOSPITAL",
        "tipo": "INICIO",
    },
    "102": {
        "nombre": "PA urgencias modificado..." if len("PA urgencias modificado") > 50 else "PA urgencias modificado",
        "descripcion": "PA urgencias modificado",
        "emisor": "HOSPITAL",
        "tipo": "INICIO",
    },
    "170": {
        "nombre": "Parte de comunicación de lesiones..." if len("Parte de comunicación de lesiones") > 50 else "Parte de comunicación de lesiones",
        "descripcion": "Parte de comunicación de lesiones",
        "emisor": "DESCONOCIDO",
        "tipo": "INICIO",
    },
    "171": {
        "nombre": "Parte de primera Asistencia ambulatoria u hospital..." if len("Parte de primera Asistencia ambulatoria u hospitalaria. (descripción que aplica al convenio 2010T y ") > 50 else "Parte de primera Asistencia ambulatoria u hospitalaria. (descripción que aplica al convenio 2010T y ",
        "descripcion": "Parte de primera Asistencia ambulatoria u hospitalaria. (descripción que aplica al convenio 2010T y ",
        "emisor": "HOSPITAL",
        "tipo": "INICIO",
    },
    "172": {
        "nombre": "PA ambulatorio modificado (descripción que aplica ..." if len("PA ambulatorio modificado (descripción que aplica al convenio 2010T y 2010U)") > 50 else "PA ambulatorio modificado (descripción que aplica al convenio 2010T y 2010U)",
        "descripcion": "PA ambulatorio modificado (descripción que aplica al convenio 2010T y 2010U)",
        "emisor": "HOSPITAL",
        "tipo": "INICIO",
    },
    "173": {
        "nombre": "PA reingreso/PA continuación gestión lesionado. (d..." if len("PA reingreso/PA continuación gestión lesionado. (descripción que aplica al convenio 2010T y 2010U)") > 50 else "PA reingreso/PA continuación gestión lesionado. (descripción que aplica al convenio 2010T y 2010U)",
        "descripcion": "PA reingreso/PA continuación gestión lesionado. (descripción que aplica al convenio 2010T y 2010U)",
        "emisor": "HOSPITAL",
        "tipo": "INICIO",
    },
    "174": {
        "nombre": "Envía parte de asistencia de reingreso modificado...." if len("Envía parte de asistencia de reingreso modificado.") > 50 else "Envía parte de asistencia de reingreso modificado.",
        "descripcion": "Envía parte de asistencia de reingreso modificado.",
        "emisor": "HOSPITAL",
        "tipo": "INICIO",
    },
    "175": {
        "nombre": "Envío parte de asistencia informativo..." if len("Envío parte de asistencia informativo") > 50 else "Envío parte de asistencia informativo",
        "descripcion": "Envío parte de asistencia informativo",
        "emisor": "HOSPITAL",
        "tipo": "INICIO",
    },
    "176": {
        "nombre": "Envío parte de asistencia de entidad no adherida a..." if len("Envío parte de asistencia de entidad no adherida a convenio") > 50 else "Envío parte de asistencia de entidad no adherida a convenio",
        "descripcion": "Envío parte de asistencia de entidad no adherida a convenio",
        "emisor": "HOSPITAL",
        "tipo": "INICIO",
    },
    "181": {
        "nombre": "Envío factura...." if len("Envío factura.") > 50 else "Envío factura.",
        "descripcion": "Envío factura.",
        "emisor": "HOSPITAL",
        "tipo": "INICIO",
    },
    "191": {
        "nombre": "Envío parte de traslado interhospitalario...." if len("Envío parte de traslado interhospitalario.") > 50 else "Envío parte de traslado interhospitalario.",
        "descripcion": "Envío parte de traslado interhospitalario.",
        "emisor": "HOSPITAL",
        "tipo": "INICIO",
    },
    "192": {
        "nombre": "Envío nuevo parte de traslado interhospitalario mo..." if len("Envío nuevo parte de traslado interhospitalario modificado") > 50 else "Envío nuevo parte de traslado interhospitalario modificado",
        "descripcion": "Envío nuevo parte de traslado interhospitalario modificado",
        "emisor": "HOSPITAL",
        "tipo": "INICIO",
    },
    "201": {
        "nombre": "Acepta parte de urgencias..." if len("Acepta parte de urgencias") > 50 else "Acepta parte de urgencias",
        "descripcion": "Acepta parte de urgencias",
        "emisor": "ASEGURADORA",
        "tipo": "RESPUESTA",
    },
    "202": {
        "nombre": "Acepta continuación tratamiento..." if len("Acepta continuación tratamiento") > 50 else "Acepta continuación tratamiento",
        "descripcion": "Acepta continuación tratamiento",
        "emisor": "ASEGURADORA",
        "tipo": "RESPUESTA",
    },
    "203": {
        "nombre": "Acepta lesionado alta especialización..." if len("Acepta lesionado alta especialización") > 50 else "Acepta lesionado alta especialización",
        "descripcion": "Acepta lesionado alta especialización",
        "emisor": "ASEGURADORA",
        "tipo": "RESPUESTA",
    },
    "270": {
        "nombre": "Subcomisión acepta parte..." if len("Subcomisión acepta parte") > 50 else "Subcomisión acepta parte",
        "descripcion": "Subcomisión acepta parte",
        "emisor": "DESCONOCIDO",
        "tipo": "RESPUESTA",
    },
    "271": {
        "nombre": "Acepta el parte de asistencia...." if len("Acepta el parte de asistencia.") > 50 else "Acepta el parte de asistencia.",
        "descripcion": "Acepta el parte de asistencia.",
        "emisor": "ASEGURADORA",
        "tipo": "RESPUESTA",
    },
    "272": {
        "nombre": "Comisión acepta parte..." if len("Comisión acepta parte") > 50 else "Comisión acepta parte",
        "descripcion": "Comisión acepta parte",
        "emisor": "DESCONOCIDO",
        "tipo": "RESPUESTA",
    },
    "275": {
        "nombre": "Subcomision acepta parte tras recurso..." if len("Subcomision acepta parte tras recurso") > 50 else "Subcomision acepta parte tras recurso",
        "descripcion": "Subcomision acepta parte tras recurso",
        "emisor": "DESCONOCIDO",
        "tipo": "RESPUESTA",
    },
    "280": {
        "nombre": "Subcomisión acepta factura..." if len("Subcomisión acepta factura") > 50 else "Subcomisión acepta factura",
        "descripcion": "Subcomisión acepta factura",
        "emisor": "DESCONOCIDO",
        "tipo": "RESPUESTA",
    },
    "281": {
        "nombre": "Acepta la factura...." if len("Acepta la factura.") > 50 else "Acepta la factura.",
        "descripcion": "Acepta la factura.",
        "emisor": "ASEGURADORA",
        "tipo": "RESPUESTA",
    },
    "284": {
        "nombre": "Comisión acepta factura..." if len("Comisión acepta factura") > 50 else "Comisión acepta factura",
        "descripcion": "Comisión acepta factura",
        "emisor": "DESCONOCIDO",
        "tipo": "RESPUESTA",
    },
    "285": {
        "nombre": "Comisión acepta pago..." if len("Comisión acepta pago") > 50 else "Comisión acepta pago",
        "descripcion": "Comisión acepta pago",
        "emisor": "DESCONOCIDO",
        "tipo": "RESPUESTA",
    },
    "287": {
        "nombre": "Subcomisión acepta pago total..." if len("Subcomisión acepta pago total") > 50 else "Subcomisión acepta pago total",
        "descripcion": "Subcomisión acepta pago total",
        "emisor": "DESCONOCIDO",
        "tipo": "RESPUESTA",
    },
    "288": {
        "nombre": "Subcomisión acepta factura tras recurso..." if len("Subcomisión acepta factura tras recurso") > 50 else "Subcomisión acepta factura tras recurso",
        "descripcion": "Subcomisión acepta factura tras recurso",
        "emisor": "DESCONOCIDO",
        "tipo": "RESPUESTA",
    },
    "301": {
        "nombre": "Comunica Continuación tratamiento..." if len("Comunica Continuación tratamiento") > 50 else "Comunica Continuación tratamiento",
        "descripcion": "Comunica Continuación tratamiento",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "302": {
        "nombre": "Comunica cambio de diagnóstico..." if len("Comunica cambio de diagnóstico") > 50 else "Comunica cambio de diagnóstico",
        "descripcion": "Comunica cambio de diagnóstico",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "303": {
        "nombre": "Acepta cambio de diagnóstico..." if len("Acepta cambio de diagnóstico") > 50 else "Acepta cambio de diagnóstico",
        "descripcion": "Acepta cambio de diagnóstico",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "304": {
        "nombre": "Rechaza cambio de diagnóstico..." if len("Rechaza cambio de diagnóstico") > 50 else "Rechaza cambio de diagnóstico",
        "descripcion": "Rechaza cambio de diagnóstico",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "305": {
        "nombre": "Solicita aclaraciones de cambio de diagnóstico..." if len("Solicita aclaraciones de cambio de diagnóstico") > 50 else "Solicita aclaraciones de cambio de diagnóstico",
        "descripcion": "Solicita aclaraciones de cambio de diagnóstico",
        "emisor": "AMBOS",
        "tipo": "DOCUMENTACION",
    },
    "306": {
        "nombre": "Envía aclaraciones cambio diagnóstico..." if len("Envía aclaraciones cambio diagnóstico") > 50 else "Envía aclaraciones cambio diagnóstico",
        "descripcion": "Envía aclaraciones cambio diagnóstico",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "307": {
        "nombre": "Abierto plazo subcomisión..." if len("Abierto plazo subcomisión") > 50 else "Abierto plazo subcomisión",
        "descripcion": "Abierto plazo subcomisión",
        "emisor": "AMBOS",
        "tipo": "DOCUMENTACION",
    },
    "308": {
        "nombre": "Acepta rechazo de factura..." if len("Acepta rechazo de factura") > 50 else "Acepta rechazo de factura",
        "descripcion": "Acepta rechazo de factura",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "309": {
        "nombre": "No acepta rechazo de factura..." if len("No acepta rechazo de factura") > 50 else "No acepta rechazo de factura",
        "descripcion": "No acepta rechazo de factura",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "310": {
        "nombre": "Vencido plazo subcomisión..." if len("Vencido plazo subcomisión") > 50 else "Vencido plazo subcomisión",
        "descripcion": "Vencido plazo subcomisión",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "311": {
        "nombre": "Solicita informe médico de evolución..." if len("Solicita informe médico de evolución") > 50 else "Solicita informe médico de evolución",
        "descripcion": "Solicita informe médico de evolución",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "312": {
        "nombre": "Pendiente Informe de alta de urgencias..." if len("Pendiente Informe de alta de urgencias") > 50 else "Pendiente Informe de alta de urgencias",
        "descripcion": "Pendiente Informe de alta de urgencias",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "313": {
        "nombre": "Vencido plazo subcomisión factura..." if len("Vencido plazo subcomisión factura") > 50 else "Vencido plazo subcomisión factura",
        "descripcion": "Vencido plazo subcomisión factura",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "314": {
        "nombre": "Solicita envío hoja de firmas..." if len("Solicita envío hoja de firmas") > 50 else "Solicita envío hoja de firmas",
        "descripcion": "Solicita envío hoja de firmas",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "315": {
        "nombre": "Solicito autorización pruebas diagnósticas..." if len("Solicito autorización pruebas diagnósticas") > 50 else "Solicito autorización pruebas diagnósticas",
        "descripcion": "Solicito autorización pruebas diagnósticas",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "316": {
        "nombre": "Autorizo pruebas diagnósticas..." if len("Autorizo pruebas diagnósticas") > 50 else "Autorizo pruebas diagnósticas",
        "descripcion": "Autorizo pruebas diagnósticas",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "317": {
        "nombre": "No autorizo pruebas diagnósticas..." if len("No autorizo pruebas diagnósticas") > 50 else "No autorizo pruebas diagnósticas",
        "descripcion": "No autorizo pruebas diagnósticas",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "318": {
        "nombre": "Ampliación de plazo...." if len("Ampliación de plazo.") > 50 else "Ampliación de plazo.",
        "descripcion": "Ampliación de plazo.",
        "emisor": "AMBOS",
        "tipo": "DOCUMENTACION",
    },
    "319": {
        "nombre": "Acepto Infiltraciones-bloqueos facetarios, nervios..." if len("Acepto Infiltraciones-bloqueos facetarios, nerviosos.") > 50 else "Acepto Infiltraciones-bloqueos facetarios, nerviosos.",
        "descripcion": "Acepto Infiltraciones-bloqueos facetarios, nerviosos.",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "320": {
        "nombre": "Rechazo Infiltraciones-bloqueos facetarios, nervio..." if len("Rechazo Infiltraciones-bloqueos facetarios, nerviosos.") > 50 else "Rechazo Infiltraciones-bloqueos facetarios, nerviosos.",
        "descripcion": "Rechazo Infiltraciones-bloqueos facetarios, nerviosos.",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "321": {
        "nombre": "Acepto ondas de choque radiales...." if len("Acepto ondas de choque radiales.") > 50 else "Acepto ondas de choque radiales.",
        "descripcion": "Acepto ondas de choque radiales.",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "322": {
        "nombre": "Rechazo ondas de choque radiales...." if len("Rechazo ondas de choque radiales.") > 50 else "Rechazo ondas de choque radiales.",
        "descripcion": "Rechazo ondas de choque radiales.",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "323": {
        "nombre": "Acepto ondas de choque focales...." if len("Acepto ondas de choque focales.") > 50 else "Acepto ondas de choque focales.",
        "descripcion": "Acepto ondas de choque focales.",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "324": {
        "nombre": "Rechazo ondas de choque focales...." if len("Rechazo ondas de choque focales.") > 50 else "Rechazo ondas de choque focales.",
        "descripcion": "Rechazo ondas de choque focales.",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "325": {
        "nombre": "Procede reducción de tarifas..." if len("Procede reducción de tarifas") > 50 else "Procede reducción de tarifas",
        "descripcion": "Procede reducción de tarifas",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "326": {
        "nombre": "Subcomisión resuelve que procede el cambio de diag..." if len("Subcomisión resuelve que procede el cambio de diagnóstico.") > 50 else "Subcomisión resuelve que procede el cambio de diagnóstico.",
        "descripcion": "Subcomisión resuelve que procede el cambio de diagnóstico.",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "327": {
        "nombre": "Subcomisión resuelve que no procede el cambio de d..." if len("Subcomisión resuelve que no procede el cambio de diagnóstico.") > 50 else "Subcomisión resuelve que no procede el cambio de diagnóstico.",
        "descripcion": "Subcomisión resuelve que no procede el cambio de diagnóstico.",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "328": {
        "nombre": "Envío datos informe alta..." if len("Envío datos informe alta") > 50 else "Envío datos informe alta",
        "descripcion": "Envío datos informe alta",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "329": {
        "nombre": "Información del informe alta..." if len("Información del informe alta") > 50 else "Información del informe alta",
        "descripcion": "Información del informe alta",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "360": {
        "nombre": "Cambio de referencia del expediente..." if len("Cambio de referencia del expediente") > 50 else "Cambio de referencia del expediente",
        "descripcion": "Cambio de referencia del expediente",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "361": {
        "nombre": "EA solicita módulo reducido..." if len("EA solicita módulo reducido") > 50 else "EA solicita módulo reducido",
        "descripcion": "EA solicita módulo reducido",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "362": {
        "nombre": "Solicita información aclaratoria...." if len("Solicita información aclaratoria.") > 50 else "Solicita información aclaratoria.",
        "descripcion": "Solicita información aclaratoria.",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "363": {
        "nombre": "Envía información aclaratoria...." if len("Envía información aclaratoria.") > 50 else "Envía información aclaratoria.",
        "descripcion": "Envía información aclaratoria.",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "364": {
        "nombre": "CS confirma aplica módulo reducido..." if len("CS confirma aplica módulo reducido") > 50 else "CS confirma aplica módulo reducido",
        "descripcion": "CS confirma aplica módulo reducido",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "365": {
        "nombre": "Justificación de envío fuera de plazo...." if len("Justificación de envío fuera de plazo.") > 50 else "Justificación de envío fuera de plazo.",
        "descripcion": "Justificación de envío fuera de plazo.",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "366": {
        "nombre": "Documentación sin catalogar...." if len("Documentación sin catalogar.") > 50 else "Documentación sin catalogar.",
        "descripcion": "Documentación sin catalogar.",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "367": {
        "nombre": "Documentación sin catalogar..." if len("Documentación sin catalogar") > 50 else "Documentación sin catalogar",
        "descripcion": "Documentación sin catalogar",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "368": {
        "nombre": "Solicita aclaración factura..." if len("Solicita aclaración factura") > 50 else "Solicita aclaración factura",
        "descripcion": "Solicita aclaración factura",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "369": {
        "nombre": "Envía aclaración factura...." if len("Envía aclaración factura.") > 50 else "Envía aclaración factura.",
        "descripcion": "Envía aclaración factura.",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "370": {
        "nombre": "Solicita autorización inicio tratamiento rehabilit..." if len("Solicita autorización inicio tratamiento rehabilitador fuera termino municipal") > 50 else "Solicita autorización inicio tratamiento rehabilitador fuera termino municipal",
        "descripcion": "Solicita autorización inicio tratamiento rehabilitador fuera termino municipal",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "371": {
        "nombre": "Autoriza tratamiento rehabilitador fuera del térmi..." if len("Autoriza tratamiento rehabilitador fuera del término municipal") > 50 else "Autoriza tratamiento rehabilitador fuera del término municipal",
        "descripcion": "Autoriza tratamiento rehabilitador fuera del término municipal",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "372": {
        "nombre": "Entidad Aseg no autoriza tratamiento rehabilitador..." if len("Entidad Aseg no autoriza tratamiento rehabilitador fuera de termino municipal") > 50 else "Entidad Aseg no autoriza tratamiento rehabilitador fuera de termino municipal",
        "descripcion": "Entidad Aseg no autoriza tratamiento rehabilitador fuera de termino municipal",
        "emisor": "AMBOS",
        "tipo": "DOCUMENTACION",
    },
    "373": {
        "nombre": "CS rechaza aplicar módulo reducido..." if len("CS rechaza aplicar módulo reducido") > 50 else "CS rechaza aplicar módulo reducido",
        "descripcion": "CS rechaza aplicar módulo reducido",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "374": {
        "nombre": "Justificante de no aseguramiento...." if len("Justificante de no aseguramiento.") > 50 else "Justificante de no aseguramiento.",
        "descripcion": "Justificante de no aseguramiento.",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "375": {
        "nombre": "Solicita aclaración declaración responsable..." if len("Solicita aclaración declaración responsable") > 50 else "Solicita aclaración declaración responsable",
        "descripcion": "Solicita aclaración declaración responsable",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "376": {
        "nombre": "Envía aclaración declaración responsable..." if len("Envía aclaración declaración responsable") > 50 else "Envía aclaración declaración responsable",
        "descripcion": "Envía aclaración declaración responsable",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "377": {
        "nombre": "Envía información alegaciones parte..." if len("Envía información alegaciones parte") > 50 else "Envía información alegaciones parte",
        "descripcion": "Envía información alegaciones parte",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "378": {
        "nombre": "Envía información alegaciones parte..." if len("Envía información alegaciones parte") > 50 else "Envía información alegaciones parte",
        "descripcion": "Envía información alegaciones parte",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "379": {
        "nombre": "Envía información alegaciones factura..." if len("Envía información alegaciones factura") > 50 else "Envía información alegaciones factura",
        "descripcion": "Envía información alegaciones factura",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "380": {
        "nombre": "Envía información alegaciones factura..." if len("Envía información alegaciones factura") > 50 else "Envía información alegaciones factura",
        "descripcion": "Envía información alegaciones factura",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "381": {
        "nombre": "Entidad notifica pago de la factura..." if len("Entidad notifica pago de la factura") > 50 else "Entidad notifica pago de la factura",
        "descripcion": "Entidad notifica pago de la factura",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "383": {
        "nombre": "EA diálogo adicional aplicación módulo..." if len("EA diálogo adicional aplicación módulo") > 50 else "EA diálogo adicional aplicación módulo",
        "descripcion": "EA diálogo adicional aplicación módulo",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "384": {
        "nombre": "CS diálogo adicional aplicación módulo..." if len("CS diálogo adicional aplicación módulo") > 50 else "CS diálogo adicional aplicación módulo",
        "descripcion": "CS diálogo adicional aplicación módulo",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "387": {
        "nombre": "EA comunica límite del conductor..." if len("EA comunica límite del conductor") > 50 else "EA comunica límite del conductor",
        "descripcion": "EA comunica límite del conductor",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "390": {
        "nombre": "EA envía aclaraciones Parte Asistencia, solicitud ..." if len("EA envía aclaraciones Parte Asistencia, solicitud subcomisión") > 50 else "EA envía aclaraciones Parte Asistencia, solicitud subcomisión",
        "descripcion": "EA envía aclaraciones Parte Asistencia, solicitud subcomisión",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "391": {
        "nombre": "CH envía aclaraciones Parte Asistencia, solicitud ..." if len("CH envía aclaraciones Parte Asistencia, solicitud subcomisión") > 50 else "CH envía aclaraciones Parte Asistencia, solicitud subcomisión",
        "descripcion": "CH envía aclaraciones Parte Asistencia, solicitud subcomisión",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "392": {
        "nombre": "CH envía aclaraciones Parte Asistencia, solicitud ..." if len("CH envía aclaraciones Parte Asistencia, solicitud Comisión") > 50 else "CH envía aclaraciones Parte Asistencia, solicitud Comisión",
        "descripcion": "CH envía aclaraciones Parte Asistencia, solicitud Comisión",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "393": {
        "nombre": "CH envía aclaraciones Factura, solicitud Comisión..." if len("CH envía aclaraciones Factura, solicitud Comisión") > 50 else "CH envía aclaraciones Factura, solicitud Comisión",
        "descripcion": "CH envía aclaraciones Factura, solicitud Comisión",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "394": {
        "nombre": "EA envía aclaraciones Factura, solicitud Comisión..." if len("EA envía aclaraciones Factura, solicitud Comisión") > 50 else "EA envía aclaraciones Factura, solicitud Comisión",
        "descripcion": "EA envía aclaraciones Factura, solicitud Comisión",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "395": {
        "nombre": "CH envía aclaraciones Factura, solicitud Comisión..." if len("CH envía aclaraciones Factura, solicitud Comisión") > 50 else "CH envía aclaraciones Factura, solicitud Comisión",
        "descripcion": "CH envía aclaraciones Factura, solicitud Comisión",
        "emisor": "HOSPITAL",
        "tipo": "DOCUMENTACION",
    },
    "398": {
        "nombre": "EA envía aclaraciones Parte Asistencia, solicitud ..." if len("EA envía aclaraciones Parte Asistencia, solicitud Comisión") > 50 else "EA envía aclaraciones Parte Asistencia, solicitud Comisión",
        "descripcion": "EA envía aclaraciones Parte Asistencia, solicitud Comisión",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "399": {
        "nombre": "EA envía aclaraciones Factura, solicitud Subcomisi..." if len("EA envía aclaraciones Factura, solicitud Subcomisión") > 50 else "EA envía aclaraciones Factura, solicitud Subcomisión",
        "descripcion": "EA envía aclaraciones Factura, solicitud Subcomisión",
        "emisor": "ASEGURADORA",
        "tipo": "DOCUMENTACION",
    },
    "401": {
        "nombre": "Parte de urgencias no cumplimentado correctamente..." if len("Parte de urgencias no cumplimentado correctamente") > 50 else "Parte de urgencias no cumplimentado correctamente",
        "descripcion": "Parte de urgencias no cumplimentado correctamente",
        "emisor": "ASEGURADORA",
        "tipo": "CONFIRMACION",
    },
    "403": {
        "nombre": "Rechaza lesionado alta especialización..." if len("Rechaza lesionado alta especialización") > 50 else "Rechaza lesionado alta especialización",
        "descripcion": "Rechaza lesionado alta especialización",
        "emisor": "ASEGURADORA",
        "tipo": "CONFIRMACION",
    },
    "421": {
        "nombre": "Rechaza declaración de responsable..." if len("Rechaza declaración de responsable") > 50 else "Rechaza declaración de responsable",
        "descripcion": "Rechaza declaración de responsable",
        "emisor": "HOSPITAL",
        "tipo": "CONFIRMACION",
    },
    "422": {
        "nombre": "Rechaza parte, transcurrido plazo 72 h. (Traumatis..." if len("Rechaza parte, transcurrido plazo 72 h. (Traumatismo menor CV)") > 50 else "Rechaza parte, transcurrido plazo 72 h. (Traumatismo menor CV)",
        "descripcion": "Rechaza parte, transcurrido plazo 72 h. (Traumatismo menor CV)",
        "emisor": "ASEGURADORA",
        "tipo": "CONFIRMACION",
    },
    "423": {
        "nombre": "Rechaza parte, lesionado no viaja en espacio desti..." if len("Rechaza parte, lesionado no viaja en espacio destinado a personas") > 50 else "Rechaza parte, lesionado no viaja en espacio destinado a personas",
        "descripcion": "Rechaza parte, lesionado no viaja en espacio destinado a personas",
        "emisor": "ASEGURADORA",
        "tipo": "CONFIRMACION",
    },
    "442": {
        "nombre": "Rechaza factura, transcurrido plazo 72 h. (Traumat..." if len("Rechaza factura, transcurrido plazo 72 h. (Traumatismo menor CV)") > 50 else "Rechaza factura, transcurrido plazo 72 h. (Traumatismo menor CV)",
        "descripcion": "Rechaza factura, transcurrido plazo 72 h. (Traumatismo menor CV)",
        "emisor": "ASEGURADORA",
        "tipo": "CONFIRMACION",
    },
    "443": {
        "nombre": "Rechaza factura, Lesionado no en espacio destinado..." if len("Rechaza factura, Lesionado no en espacio destinado a personas") > 50 else "Rechaza factura, Lesionado no en espacio destinado a personas",
        "descripcion": "Rechaza factura, Lesionado no en espacio destinado a personas",
        "emisor": "ASEGURADORA",
        "tipo": "CONFIRMACION",
    },
    "471": {
        "nombre": "Rechazo del parte de asistencia...." if len("Rechazo del parte de asistencia.") > 50 else "Rechazo del parte de asistencia.",
        "descripcion": "Rechazo del parte de asistencia.",
        "emisor": "ASEGURADORA",
        "tipo": "CONFIRMACION",
    },
    "472": {
        "nombre": "Parte de asistencia no cumplimentado correctamente..." if len("Parte de asistencia no cumplimentado correctamente.") > 50 else "Parte de asistencia no cumplimentado correctamente.",
        "descripcion": "Parte de asistencia no cumplimentado correctamente.",
        "emisor": "ASEGURADORA",
        "tipo": "CONFIRMACION",
    },
    "473": {
        "nombre": "No hay acuerdo con el contenido del parte de asist..." if len("No hay acuerdo con el contenido del parte de asistencia.") > 50 else "No hay acuerdo con el contenido del parte de asistencia.",
        "descripcion": "No hay acuerdo con el contenido del parte de asistencia.",
        "emisor": "ASEGURADORA",
        "tipo": "CONFIRMACION",
    },
    "474": {
        "nombre": "Rechaza el parte por no asegurar al vehículo...." if len("Rechaza el parte por no asegurar al vehículo.") > 50 else "Rechaza el parte por no asegurar al vehículo.",
        "descripcion": "Rechaza el parte por no asegurar al vehículo.",
        "emisor": "ASEGURADORA",
        "tipo": "CONFIRMACION",
    },
    "475": {
        "nombre": "No corresponde el pago (estipulación de Convenio)...." if len("No corresponde el pago (estipulación de Convenio).") > 50 else "No corresponde el pago (estipulación de Convenio).",
        "descripcion": "No corresponde el pago (estipulación de Convenio).",
        "emisor": "ASEGURADORA",
        "tipo": "CONFIRMACION",
    },
    "476": {
        "nombre": "Rechaza parte, no corresponde pago entidad no adhe..." if len("Rechaza parte, no corresponde pago entidad no adherida") > 50 else "Rechaza parte, no corresponde pago entidad no adherida",
        "descripcion": "Rechaza parte, no corresponde pago entidad no adherida",
        "emisor": "ASEGURADORA",
        "tipo": "CONFIRMACION",
    },
    "477": {
        "nombre": "Rechaza Parte de Asistencia, conductor sin cobertu..." if len("Rechaza Parte de Asistencia, conductor sin cobertura") > 50 else "Rechaza Parte de Asistencia, conductor sin cobertura",
        "descripcion": "Rechaza Parte de Asistencia, conductor sin cobertura",
        "emisor": "AMBOS",
        "tipo": "CONFIRMACION",
    },
    "478": {
        "nombre": "Rechaza parte, sí existe seguro..." if len("Rechaza parte, sí existe seguro") > 50 else "Rechaza parte, sí existe seguro",
        "descripcion": "Rechaza parte, sí existe seguro",
        "emisor": "HOSPITAL",
        "tipo": "CONFIRMACION",
    },
    "481": {
        "nombre": "Rechaza factura: asistencia posterior a comunicaci..." if len("Rechaza factura: asistencia posterior a comunicación no aceptación (Descripción que aplica al conven") > 50 else "Rechaza factura: asistencia posterior a comunicación no aceptación (Descripción que aplica al conven",
        "descripcion": "Rechaza factura: asistencia posterior a comunicación no aceptación (Descripción que aplica al conven",
        "emisor": "ASEGURADORA",
        "tipo": "CONFIRMACION",
    },
    "482": {
        "nombre": "Rechaza factura por no asegurar el vehículo..." if len("Rechaza factura por no asegurar el vehículo") > 50 else "Rechaza factura por no asegurar el vehículo",
        "descripcion": "Rechaza factura por no asegurar el vehículo",
        "emisor": "ASEGURADORA",
        "tipo": "CONFIRMACION",
    },
    "483": {
        "nombre": "Rechaza factura por no aplicar convenio..." if len("Rechaza factura por no aplicar convenio") > 50 else "Rechaza factura por no aplicar convenio",
        "descripcion": "Rechaza factura por no aplicar convenio",
        "emisor": "ASEGURADORA",
        "tipo": "CONFIRMACION",
    },
    "484": {
        "nombre": "Rechaza factura por existir seguro..." if len("Rechaza factura por existir seguro") > 50 else "Rechaza factura por existir seguro",
        "descripcion": "Rechaza factura por existir seguro",
        "emisor": "DESCONOCIDO",
        "tipo": "CONFIRMACION",
    },
    "485": {
        "nombre": "Rechaza factura, no corresponde pago entidad no ad..." if len("Rechaza factura, no corresponde pago entidad no adherida") > 50 else "Rechaza factura, no corresponde pago entidad no adherida",
        "descripcion": "Rechaza factura, no corresponde pago entidad no adherida",
        "emisor": "ASEGURADORA",
        "tipo": "CONFIRMACION",
    },
    "486": {
        "nombre": "Rechazo factura, transcurso de los plazos previsto..." if len("Rechazo factura, transcurso de los plazos previstos en el Convenio") > 50 else "Rechazo factura, transcurso de los plazos previstos en el Convenio",
        "descripcion": "Rechazo factura, transcurso de los plazos previstos en el Convenio",
        "emisor": "ASEGURADORA",
        "tipo": "CONFIRMACION",
    },
    "487": {
        "nombre": "Rechaza factura: discrepancia o desproporción entr..." if len("Rechaza factura: discrepancia o desproporción entre diagnóstico y el tratamiento. (Descripción que a") > 50 else "Rechaza factura: discrepancia o desproporción entre diagnóstico y el tratamiento. (Descripción que a",
        "descripcion": "Rechaza factura: discrepancia o desproporción entre diagnóstico y el tratamiento. (Descripción que a",
        "emisor": "ASEGURADORA",
        "tipo": "CONFIRMACION",
    },
    "488": {
        "nombre": "Rechaza factura, prestación no autorizada..." if len("Rechaza factura, prestación no autorizada") > 50 else "Rechaza factura, prestación no autorizada",
        "descripcion": "Rechaza factura, prestación no autorizada",
        "emisor": "ASEGURADORA",
        "tipo": "CONFIRMACION",
    },
    "492": {
        "nombre": "Rechaza parte, no se trata de un hecho de la circu..." if len("Rechaza parte, no se trata de un hecho de la circulación") > 50 else "Rechaza parte, no se trata de un hecho de la circulación",
        "descripcion": "Rechaza parte, no se trata de un hecho de la circulación",
        "emisor": "AMBOS",
        "tipo": "CONFIRMACION",
    },
    "494": {
        "nombre": "Rechaza parte, transcurso plazos previstos en Conv..." if len("Rechaza parte, transcurso plazos previstos en Convenio") > 50 else "Rechaza parte, transcurso plazos previstos en Convenio",
        "descripcion": "Rechaza parte, transcurso plazos previstos en Convenio",
        "emisor": "AMBOS",
        "tipo": "CONFIRMACION",
    },
    "495": {
        "nombre": "Rechaza parte, existencia probada de fraude..." if len("Rechaza parte, existencia probada de fraude") > 50 else "Rechaza parte, existencia probada de fraude",
        "descripcion": "Rechaza parte, existencia probada de fraude",
        "emisor": "AMBOS",
        "tipo": "CONFIRMACION",
    },
    "496": {
        "nombre": "Rechaza parte, falta de relación causal, criterio ..." if len("Rechaza parte, falta de relación causal, criterio cronológico") > 50 else "Rechaza parte, falta de relación causal, criterio cronológico",
        "descripcion": "Rechaza parte, falta de relación causal, criterio cronológico",
        "emisor": "AMBOS",
        "tipo": "CONFIRMACION",
    },
    "497": {
        "nombre": "Rechaza parte, falta de relación causal, criterio ..." if len("Rechaza parte, falta de relación causal, criterio de intensidad") > 50 else "Rechaza parte, falta de relación causal, criterio de intensidad",
        "descripcion": "Rechaza parte, falta de relación causal, criterio de intensidad",
        "emisor": "AMBOS",
        "tipo": "CONFIRMACION",
    },
    "498": {
        "nombre": "Rechaza parte, falta de relación causal, criterio ..." if len("Rechaza parte, falta de relación causal, criterio topográfico") > 50 else "Rechaza parte, falta de relación causal, criterio topográfico",
        "descripcion": "Rechaza parte, falta de relación causal, criterio topográfico",
        "emisor": "AMBOS",
        "tipo": "CONFIRMACION",
    },
    "499": {
        "nombre": "Rechaza parte, falta de relación causal, criterio ..." if len("Rechaza parte, falta de relación causal, criterio de exclusión") > 50 else "Rechaza parte, falta de relación causal, criterio de exclusión",
        "descripcion": "Rechaza parte, falta de relación causal, criterio de exclusión",
        "emisor": "AMBOS",
        "tipo": "CONFIRMACION",
    },
    "500": {
        "nombre": "Abandona gestión expediente..." if len("Abandona gestión expediente") > 50 else "Abandona gestión expediente",
        "descripcion": "Abandona gestión expediente",
        "emisor": "HOSPITAL",
        "tipo": "FACTURACION",
    },
    "501": {
        "nombre": "Baja de expediente con pago..." if len("Baja de expediente con pago") > 50 else "Baja de expediente con pago",
        "descripcion": "Baja de expediente con pago",
        "emisor": "HOSPITAL",
        "tipo": "FACTURACION",
    },
    "502": {
        "nombre": "Baja del expediente..." if len("Baja del expediente") > 50 else "Baja del expediente",
        "descripcion": "Baja del expediente",
        "emisor": "DESCONOCIDO",
        "tipo": "FACTURACION",
    },
    "503": {
        "nombre": "Acepta rechazo de parte..." if len("Acepta rechazo de parte") > 50 else "Acepta rechazo de parte",
        "descripcion": "Acepta rechazo de parte",
        "emisor": "DESCONOCIDO",
        "tipo": "FACTURACION",
    },
    "504": {
        "nombre": "Baja expediente no convenio...." if len("Baja expediente no convenio.") > 50 else "Baja expediente no convenio.",
        "descripcion": "Baja expediente no convenio.",
        "emisor": "HOSPITAL",
        "tipo": "FACTURACION",
    },
    "570": {
        "nombre": "Abandona gestión de factura...." if len("Abandona gestión de factura.") > 50 else "Abandona gestión de factura.",
        "descripcion": "Abandona gestión de factura.",
        "emisor": "DESCONOCIDO",
        "tipo": "FACTURACION",
    },
    "572": {
        "nombre": "Subcomisión No procede parte..." if len("Subcomisión No procede parte") > 50 else "Subcomisión No procede parte",
        "descripcion": "Subcomisión No procede parte",
        "emisor": "DESCONOCIDO",
        "tipo": "FACTURACION",
    },
    "573": {
        "nombre": "Subcomisión resuelve no procede factura (descripci..." if len("Subcomisión resuelve no procede factura (descripción que aplica al convenio 2010T)") > 50 else "Subcomisión resuelve no procede factura (descripción que aplica al convenio 2010T)",
        "descripcion": "Subcomisión resuelve no procede factura (descripción que aplica al convenio 2010T)",
        "emisor": "DESCONOCIDO",
        "tipo": "FACTURACION",
    },
    "574": {
        "nombre": "Subcomisión no procede parte tras recurso..." if len("Subcomisión no procede parte tras recurso") > 50 else "Subcomisión no procede parte tras recurso",
        "descripcion": "Subcomisión no procede parte tras recurso",
        "emisor": "DESCONOCIDO",
        "tipo": "FACTURACION",
    },
    "575": {
        "nombre": "Comisión resuelve no procede parte..." if len("Comisión resuelve no procede parte") > 50 else "Comisión resuelve no procede parte",
        "descripcion": "Comisión resuelve no procede parte",
        "emisor": "DESCONOCIDO",
        "tipo": "FACTURACION",
    },
    "576": {
        "nombre": "Comisión resuelve no procede factura..." if len("Comisión resuelve no procede factura") > 50 else "Comisión resuelve no procede factura",
        "descripcion": "Comisión resuelve no procede factura",
        "emisor": "DESCONOCIDO",
        "tipo": "FACTURACION",
    },
    "577": {
        "nombre": "Subcomisión no procede factura tras recurso..." if len("Subcomisión no procede factura tras recurso") > 50 else "Subcomisión no procede factura tras recurso",
        "descripcion": "Subcomisión no procede factura tras recurso",
        "emisor": "DESCONOCIDO",
        "tipo": "FACTURACION",
    },
    "578": {
        "nombre": "Subcomisión resuelve no procede pago total..." if len("Subcomisión resuelve no procede pago total") > 50 else "Subcomisión resuelve no procede pago total",
        "descripcion": "Subcomisión resuelve no procede pago total",
        "emisor": "DESCONOCIDO",
        "tipo": "FACTURACION",
    },
    "579": {
        "nombre": "Comisión resuelve No procede total..." if len("Comisión resuelve No procede total") > 50 else "Comisión resuelve No procede total",
        "descripcion": "Comisión resuelve No procede total",
        "emisor": "DESCONOCIDO",
        "tipo": "FACTURACION",
    },
    "580": {
        "nombre": "Envía factura rectificativa de anulación..." if len("Envía factura rectificativa de anulación") > 50 else "Envía factura rectificativa de anulación",
        "descripcion": "Envía factura rectificativa de anulación",
        "emisor": "HOSPITAL",
        "tipo": "FACTURACION",
    },
    "581": {
        "nombre": "Confirma factura abonada totalmente..." if len("Confirma factura abonada totalmente") > 50 else "Confirma factura abonada totalmente",
        "descripcion": "Confirma factura abonada totalmente",
        "emisor": "HOSPITAL",
        "tipo": "FACTURACION",
    },
    "582": {
        "nombre": "Confirma factura abonada parcialmente..." if len("Confirma factura abonada parcialmente") > 50 else "Confirma factura abonada parcialmente",
        "descripcion": "Confirma factura abonada parcialmente",
        "emisor": "HOSPITAL",
        "tipo": "FACTURACION",
    },
    "583": {
        "nombre": "Factura sin abono por Convenio..." if len("Factura sin abono por Convenio") > 50 else "Factura sin abono por Convenio",
        "descripcion": "Factura sin abono por Convenio",
        "emisor": "HOSPITAL",
        "tipo": "FACTURACION",
    },
    "584": {
        "nombre": "Cierre factura. No procede...." if len("Cierre factura. No procede.") > 50 else "Cierre factura. No procede.",
        "descripcion": "Cierre factura. No procede.",
        "emisor": "DESCONOCIDO",
        "tipo": "FACTURACION",
    },
    "585": {
        "nombre": "Envía factura rectificativa de importes..." if len("Envía factura rectificativa de importes") > 50 else "Envía factura rectificativa de importes",
        "descripcion": "Envía factura rectificativa de importes",
        "emisor": "HOSPITAL",
        "tipo": "FACTURACION",
    },
    "586": {
        "nombre": "Cierre factura. No procede total..." if len("Cierre factura. No procede total") > 50 else "Cierre factura. No procede total",
        "descripcion": "Cierre factura. No procede total",
        "emisor": "DESCONOCIDO",
        "tipo": "FACTURACION",
    },
    "587": {
        "nombre": "Cierre factura con embargo..." if len("Cierre factura con embargo") > 50 else "Cierre factura con embargo",
        "descripcion": "Cierre factura con embargo",
        "emisor": "HOSPITAL",
        "tipo": "FACTURACION",
    },
    "652": {
        "nombre": "Alegaciones Subcomisión por parte..." if len("Alegaciones Subcomisión por parte") > 50 else "Alegaciones Subcomisión por parte",
        "descripcion": "Alegaciones Subcomisión por parte",
        "emisor": "AMBOS",
        "tipo": "PAGO",
    },
    "653": {
        "nombre": "Alegaciones Subcomisión factura..." if len("Alegaciones Subcomisión factura") > 50 else "Alegaciones Subcomisión factura",
        "descripcion": "Alegaciones Subcomisión factura",
        "emisor": "AMBOS",
        "tipo": "PAGO",
    },
    "655": {
        "nombre": "Alegaciones subcomisión cambio de diagnóstico (201..." if len("Alegaciones subcomisión cambio de diagnóstico (2010U)") > 50 else "Alegaciones subcomisión cambio de diagnóstico (2010U)",
        "descripcion": "Alegaciones subcomisión cambio de diagnóstico (2010U)",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "662": {
        "nombre": "Subcomisión automatizada por Parte..." if len("Subcomisión automatizada por Parte") > 50 else "Subcomisión automatizada por Parte",
        "descripcion": "Subcomisión automatizada por Parte",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "663": {
        "nombre": "Subcomisión automatizada por Factura..." if len("Subcomisión automatizada por Factura") > 50 else "Subcomisión automatizada por Factura",
        "descripcion": "Subcomisión automatizada por Factura",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "664": {
        "nombre": "Envío a subcomisión disconformidad reducción tarif..." if len("Envío a subcomisión disconformidad reducción tarifa") > 50 else "Envío a subcomisión disconformidad reducción tarifa",
        "descripcion": "Envío a subcomisión disconformidad reducción tarifa",
        "emisor": "HOSPITAL",
        "tipo": "PAGO",
    },
    "665": {
        "nombre": "Subcomision automatizada por cambio de diagnóstico..." if len("Subcomision automatizada por cambio de diagnóstico (2010U)") > 50 else "Subcomision automatizada por cambio de diagnóstico (2010U)",
        "descripcion": "Subcomision automatizada por cambio de diagnóstico (2010U)",
        "emisor": "HOSPITAL",
        "tipo": "PAGO",
    },
    "666": {
        "nombre": "Parte elevado a Comisión..." if len("Parte elevado a Comisión") > 50 else "Parte elevado a Comisión",
        "descripcion": "Parte elevado a Comisión",
        "emisor": "AMBOS",
        "tipo": "PAGO",
    },
    "667": {
        "nombre": "Factura elevada a Comisión..." if len("Factura elevada a Comisión") > 50 else "Factura elevada a Comisión",
        "descripcion": "Factura elevada a Comisión",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "669": {
        "nombre": "Subcomisión solicita documentación aclaración part..." if len("Subcomisión solicita documentación aclaración parte") > 50 else "Subcomisión solicita documentación aclaración parte",
        "descripcion": "Subcomisión solicita documentación aclaración parte",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "670": {
        "nombre": "Interlocutores por Parte..." if len("Interlocutores por Parte") > 50 else "Interlocutores por Parte",
        "descripcion": "Interlocutores por Parte",
        "emisor": "AMBOS",
        "tipo": "PAGO",
    },
    "671": {
        "nombre": "Interlocutores por Factura..." if len("Interlocutores por Factura") > 50 else "Interlocutores por Factura",
        "descripcion": "Interlocutores por Factura",
        "emisor": "AMBOS",
        "tipo": "PAGO",
    },
    "672": {
        "nombre": "Fin gestión Parte en CAS. Gestionar con subcomisió..." if len("Fin gestión Parte en CAS. Gestionar con subcomisión no automatizada") > 50 else "Fin gestión Parte en CAS. Gestionar con subcomisión no automatizada",
        "descripcion": "Fin gestión Parte en CAS. Gestionar con subcomisión no automatizada",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "673": {
        "nombre": "Fin gestión Factura en CAS. Gestionar con subcomis..." if len("Fin gestión Factura en CAS. Gestionar con subcomisión no automatizada") > 50 else "Fin gestión Factura en CAS. Gestionar con subcomisión no automatizada",
        "descripcion": "Fin gestión Factura en CAS. Gestionar con subcomisión no automatizada",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "674": {
        "nombre": "Subcomisión por falta de pago..." if len("Subcomisión por falta de pago") > 50 else "Subcomisión por falta de pago",
        "descripcion": "Subcomisión por falta de pago",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "676": {
        "nombre": "CCS Pago pendiente..." if len("CCS Pago pendiente") > 50 else "CCS Pago pendiente",
        "descripcion": "CCS Pago pendiente",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "677": {
        "nombre": "Comisión solicita documentación aclaración Parte..." if len("Comisión solicita documentación aclaración Parte") > 50 else "Comisión solicita documentación aclaración Parte",
        "descripcion": "Comisión solicita documentación aclaración Parte",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "678": {
        "nombre": "Subcomisión solicita documentación aclaración Fact..." if len("Subcomisión solicita documentación aclaración Factura") > 50 else "Subcomisión solicita documentación aclaración Factura",
        "descripcion": "Subcomisión solicita documentación aclaración Factura",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "679": {
        "nombre": "Comisión solicita documentación aclaración Factura..." if len("Comisión solicita documentación aclaración Factura") > 50 else "Comisión solicita documentación aclaración Factura",
        "descripcion": "Comisión solicita documentación aclaración Factura",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "682": {
        "nombre": "Resolución firme subcomisión acepta parte..." if len("Resolución firme subcomisión acepta parte") > 50 else "Resolución firme subcomisión acepta parte",
        "descripcion": "Resolución firme subcomisión acepta parte",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "683": {
        "nombre": "Resolución firme subcomisión no procede parte..." if len("Resolución firme subcomisión no procede parte") > 50 else "Resolución firme subcomisión no procede parte",
        "descripcion": "Resolución firme subcomisión no procede parte",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "684": {
        "nombre": "Resolución firme subcomisión acepta factura..." if len("Resolución firme subcomisión acepta factura") > 50 else "Resolución firme subcomisión acepta factura",
        "descripcion": "Resolución firme subcomisión acepta factura",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "685": {
        "nombre": "Resolución firme subcomisión no procede factura..." if len("Resolución firme subcomisión no procede factura") > 50 else "Resolución firme subcomisión no procede factura",
        "descripcion": "Resolución firme subcomisión no procede factura",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "686": {
        "nombre": "Interlocutores por paciente alta especialización..." if len("Interlocutores por paciente alta especialización") > 50 else "Interlocutores por paciente alta especialización",
        "descripcion": "Interlocutores por paciente alta especialización",
        "emisor": "AMBOS",
        "tipo": "PAGO",
    },
    "687": {
        "nombre": "Fin gestión lesionado-alta complejidad en CAS. Ges..." if len("Fin gestión lesionado-alta complejidad en CAS. Gestionar con subcomisión no automatizada") > 50 else "Fin gestión lesionado-alta complejidad en CAS. Gestionar con subcomisión no automatizada",
        "descripcion": "Fin gestión lesionado-alta complejidad en CAS. Gestionar con subcomisión no automatizada",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "701": {
        "nombre": "Envío fuera de plazo (15 días naturales) del parte..." if len("Envío fuera de plazo (15 días naturales) del parte de urgencia") > 50 else "Envío fuera de plazo (15 días naturales) del parte de urgencia",
        "descripcion": "Envío fuera de plazo (15 días naturales) del parte de urgencia",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "702": {
        "nombre": "Envío fuera de plazo (15 días naturales) del parte..." if len("Envío fuera de plazo (15 días naturales) del parte de primera asistencia ambulatoria u hospitalaria") > 50 else "Envío fuera de plazo (15 días naturales) del parte de primera asistencia ambulatoria u hospitalaria",
        "descripcion": "Envío fuera de plazo (15 días naturales) del parte de primera asistencia ambulatoria u hospitalaria",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "703": {
        "nombre": "Envío fuera de plazo (15 días naturales) del infor..." if len("Envío fuera de plazo (15 días naturales) del informe de evolución") > 50 else "Envío fuera de plazo (15 días naturales) del informe de evolución",
        "descripcion": "Envío fuera de plazo (15 días naturales) del informe de evolución",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "704": {
        "nombre": "Comunicación fuera de plazo (15 días naturales) de..." if len("Comunicación fuera de plazo (15 días naturales) del cambio de diagnóstico.") > 50 else "Comunicación fuera de plazo (15 días naturales) del cambio de diagnóstico.",
        "descripcion": "Comunicación fuera de plazo (15 días naturales) del cambio de diagnóstico.",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "705": {
        "nombre": "Presentación de las facturas de las asistencias pr..." if len("Presentación de las facturas de las asistencias prestadas por los centros sanitarios") > 50 else "Presentación de las facturas de las asistencias prestadas por los centros sanitarios",
        "descripcion": "Presentación de las facturas de las asistencias prestadas por los centros sanitarios",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "715": {
        "nombre": "Aviso caducidad factura...." if len("Aviso caducidad factura.") > 50 else "Aviso caducidad factura.",
        "descripcion": "Aviso caducidad factura.",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "716": {
        "nombre": "Aviso envío fuera de plazo (15 días naturales) del..." if len("Aviso envío fuera de plazo (15 días naturales) del informe de evolución") > 50 else "Aviso envío fuera de plazo (15 días naturales) del informe de evolución",
        "descripcion": "Aviso envío fuera de plazo (15 días naturales) del informe de evolución",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "717": {
        "nombre": "Aviso presentación de las facturas de las asistenc..." if len("Aviso presentación de las facturas de las asistencias prestadas por los CS") > 50 else "Aviso presentación de las facturas de las asistencias prestadas por los CS",
        "descripcion": "Aviso presentación de las facturas de las asistencias prestadas por los CS",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "801": {
        "nombre": "Solicitud de autorización para calificación de les..." if len("Solicitud de autorización para calificación de lesionado alta especialización") > 50 else "Solicitud de autorización para calificación de lesionado alta especialización",
        "descripcion": "Solicitud de autorización para calificación de lesionado alta especialización",
        "emisor": "HOSPITAL",
        "tipo": "RECLAMACION",
    },
    "806": {
        "nombre": "Informe cambio diagnóstico..." if len("Informe cambio diagnóstico") > 50 else "Informe cambio diagnóstico",
        "descripcion": "Informe cambio diagnóstico",
        "emisor": "HOSPITAL",
        "tipo": "RECLAMACION",
    },
    "811": {
        "nombre": "Informe médico de evolución..." if len("Informe médico de evolución") > 50 else "Informe médico de evolución",
        "descripcion": "Informe médico de evolución",
        "emisor": "HOSPITAL",
        "tipo": "RECLAMACION",
    },
    "814": {
        "nombre": "Envía documento hoja de firmas..." if len("Envía documento hoja de firmas") > 50 else "Envía documento hoja de firmas",
        "descripcion": "Envía documento hoja de firmas",
        "emisor": "HOSPITAL",
        "tipo": "RECLAMACION",
    },
    "821": {
        "nombre": "Envío documento Declaración responsable..." if len("Envío documento Declaración responsable") > 50 else "Envío documento Declaración responsable",
        "descripcion": "Envío documento Declaración responsable",
        "emisor": "HOSPITAL",
        "tipo": "RECLAMACION",
    },
    "822": {
        "nombre": "Envío nueva declaración responsable..." if len("Envío nueva declaración responsable") > 50 else "Envío nueva declaración responsable",
        "descripcion": "Envío nueva declaración responsable",
        "emisor": "HOSPITAL",
        "tipo": "RECLAMACION",
    },
    "823": {
        "nombre": "Solicito autorización Infiltraciones-bloqueos face..." if len("Solicito autorización Infiltraciones-bloqueos facetarios, nerviosos") > 50 else "Solicito autorización Infiltraciones-bloqueos facetarios, nerviosos",
        "descripcion": "Solicito autorización Infiltraciones-bloqueos facetarios, nerviosos",
        "emisor": "AMBOS",
        "tipo": "RECLAMACION",
    },
    "824": {
        "nombre": "Solicito autorización ondas de choque radiales..." if len("Solicito autorización ondas de choque radiales") > 50 else "Solicito autorización ondas de choque radiales",
        "descripcion": "Solicito autorización ondas de choque radiales",
        "emisor": "AMBOS",
        "tipo": "RECLAMACION",
    },
    "825": {
        "nombre": "Solicito autorización ondas de choque focales..." if len("Solicito autorización ondas de choque focales") > 50 else "Solicito autorización ondas de choque focales",
        "descripcion": "Solicito autorización ondas de choque focales",
        "emisor": "AMBOS",
        "tipo": "RECLAMACION",
    },
    "828": {
        "nombre": "Envío informe de alta (Sanidad Pública)..." if len("Envío informe de alta (Sanidad Pública)") > 50 else "Envío informe de alta (Sanidad Pública)",
        "descripcion": "Envío informe de alta (Sanidad Pública)",
        "emisor": "HOSPITAL",
        "tipo": "RECLAMACION",
    },
    "841": {
        "nombre": "Justificante de rechazo parte (acompañado de los m..." if len("Justificante de rechazo parte (acompañado de los mensajes de rechazo que implican envío de justifica") > 50 else "Justificante de rechazo parte (acompañado de los mensajes de rechazo que implican envío de justifica",
        "descripcion": "Justificante de rechazo parte (acompañado de los mensajes de rechazo que implican envío de justifica",
        "emisor": "AMBOS",
        "tipo": "RECLAMACION",
    },
    "861": {
        "nombre": "EA justifica aplicar módulo reducido..." if len("EA justifica aplicar módulo reducido") > 50 else "EA justifica aplicar módulo reducido",
        "descripcion": "EA justifica aplicar módulo reducido",
        "emisor": "ASEGURADORA",
        "tipo": "RECLAMACION",
    },
    "863": {
        "nombre": "Envía Documentos originales información aclaratori..." if len("Envía Documentos originales información aclaratoria.") > 50 else "Envía Documentos originales información aclaratoria.",
        "descripcion": "Envía Documentos originales información aclaratoria.",
        "emisor": "HOSPITAL",
        "tipo": "RECLAMACION",
    },
    "864": {
        "nombre": "Centro sanitario justifica diálogo aplicación módu..." if len("Centro sanitario justifica diálogo aplicación módulo reducido") > 50 else "Centro sanitario justifica diálogo aplicación módulo reducido",
        "descripcion": "Centro sanitario justifica diálogo aplicación módulo reducido",
        "emisor": "HOSPITAL",
        "tipo": "RECLAMACION",
    },
    "865": {
        "nombre": "Documento original de justificación de envío fuera..." if len("Documento original de justificación de envío fuera de plazo.") > 50 else "Documento original de justificación de envío fuera de plazo.",
        "descripcion": "Documento original de justificación de envío fuera de plazo.",
        "emisor": "HOSPITAL",
        "tipo": "RECLAMACION",
    },
    "866": {
        "nombre": "Documentación original sin catalogar...." if len("Documentación original sin catalogar.") > 50 else "Documentación original sin catalogar.",
        "descripcion": "Documentación original sin catalogar.",
        "emisor": "HOSPITAL",
        "tipo": "RECLAMACION",
    },
    "867": {
        "nombre": "Documentación original sin catalogar...." if len("Documentación original sin catalogar.") > 50 else "Documentación original sin catalogar.",
        "descripcion": "Documentación original sin catalogar.",
        "emisor": "ASEGURADORA",
        "tipo": "RECLAMACION",
    },
    "869": {
        "nombre": "Envía Documentos originales de aclaración factura..." if len("Envía Documentos originales de aclaración factura") > 50 else "Envía Documentos originales de aclaración factura",
        "descripcion": "Envía Documentos originales de aclaración factura",
        "emisor": "HOSPITAL",
        "tipo": "RECLAMACION",
    },
    "870": {
        "nombre": "Documentación Justificante de rechazo factura (aco..." if len("Documentación Justificante de rechazo factura (acompañado del 487)") > 50 else "Documentación Justificante de rechazo factura (acompañado del 487)",
        "descripcion": "Documentación Justificante de rechazo factura (acompañado del 487)",
        "emisor": "AMBOS",
        "tipo": "RECLAMACION",
    },
    "874": {
        "nombre": "Documento original de justificante de no asegurami..." if len("Documento original de justificante de no aseguramiento.") > 50 else "Documento original de justificante de no aseguramiento.",
        "descripcion": "Documento original de justificante de no aseguramiento.",
        "emisor": "ASEGURADORA",
        "tipo": "RECLAMACION",
    },
    "876": {
        "nombre": "Envía doc. original aclaración declaración respons..." if len("Envía doc. original aclaración declaración responsable") > 50 else "Envía doc. original aclaración declaración responsable",
        "descripcion": "Envía doc. original aclaración declaración responsable",
        "emisor": "HOSPITAL",
        "tipo": "RECLAMACION",
    },
    "877": {
        "nombre": "Doc. original información alegaciones parte..." if len("Doc. original información alegaciones parte") > 50 else "Doc. original información alegaciones parte",
        "descripcion": "Doc. original información alegaciones parte",
        "emisor": "HOSPITAL",
        "tipo": "RECLAMACION",
    },
    "878": {
        "nombre": "Doc. original información alegaciones parte..." if len("Doc. original información alegaciones parte") > 50 else "Doc. original información alegaciones parte",
        "descripcion": "Doc. original información alegaciones parte",
        "emisor": "ASEGURADORA",
        "tipo": "RECLAMACION",
    },
    "879": {
        "nombre": "Doc. original información alegaciones factura..." if len("Doc. original información alegaciones factura") > 50 else "Doc. original información alegaciones factura",
        "descripcion": "Doc. original información alegaciones factura",
        "emisor": "HOSPITAL",
        "tipo": "RECLAMACION",
    },
    "880": {
        "nombre": "Doc. original información alegaciones factura..." if len("Doc. original información alegaciones factura") > 50 else "Doc. original información alegaciones factura",
        "descripcion": "Doc. original información alegaciones factura",
        "emisor": "ASEGURADORA",
        "tipo": "RECLAMACION",
    },
    "881": {
        "nombre": "Informe de alta de urgencias..." if len("Informe de alta de urgencias") > 50 else "Informe de alta de urgencias",
        "descripcion": "Informe de alta de urgencias",
        "emisor": "HOSPITAL",
        "tipo": "RECLAMACION",
    },
    "885": {
        "nombre": "Envío informe de alta..." if len("Envío informe de alta") > 50 else "Envío informe de alta",
        "descripcion": "Envío informe de alta",
        "emisor": "HOSPITAL",
        "tipo": "RECLAMACION",
    },
    "890": {
        "nombre": "Envía documentación solicitud subcomisión (adicion..." if len("Envía documentación solicitud subcomisión (adicional) (descripción que aplica al convenio 2010T)") > 50 else "Envía documentación solicitud subcomisión (adicional) (descripción que aplica al convenio 2010T)",
        "descripcion": "Envía documentación solicitud subcomisión (adicional) (descripción que aplica al convenio 2010T)",
        "emisor": "ASEGURADORA",
        "tipo": "RECLAMACION",
    },
    "891": {
        "nombre": "Envía documentación solicitud subcomisión (adicion..." if len("Envía documentación solicitud subcomisión (adicional) (descripción que aplica al convenio 2010T)") > 50 else "Envía documentación solicitud subcomisión (adicional) (descripción que aplica al convenio 2010T)",
        "descripcion": "Envía documentación solicitud subcomisión (adicional) (descripción que aplica al convenio 2010T)",
        "emisor": "HOSPITAL",
        "tipo": "RECLAMACION",
    },
    "892": {
        "nombre": "Envía documentación solicitud comisión (adicional)..." if len("Envía documentación solicitud comisión (adicional) (descripción que aplica al convenio 2010T)") > 50 else "Envía documentación solicitud comisión (adicional) (descripción que aplica al convenio 2010T)",
        "descripcion": "Envía documentación solicitud comisión (adicional) (descripción que aplica al convenio 2010T)",
        "emisor": "HOSPITAL",
        "tipo": "RECLAMACION",
    },
    "893": {
        "nombre": "Envía documentación solicitud subcomisión Factura ..." if len("Envía documentación solicitud subcomisión Factura (adicional) (descripción que aplica al convenio 20") > 50 else "Envía documentación solicitud subcomisión Factura (adicional) (descripción que aplica al convenio 20",
        "descripcion": "Envía documentación solicitud subcomisión Factura (adicional) (descripción que aplica al convenio 20",
        "emisor": "HOSPITAL",
        "tipo": "RECLAMACION",
    },
    "894": {
        "nombre": "Envía documentación solicitud comisión Factura (ad..." if len("Envía documentación solicitud comisión Factura (adicional) (descripción que aplica al convenio 2010T") > 50 else "Envía documentación solicitud comisión Factura (adicional) (descripción que aplica al convenio 2010T",
        "descripcion": "Envía documentación solicitud comisión Factura (adicional) (descripción que aplica al convenio 2010T",
        "emisor": "ASEGURADORA",
        "tipo": "RECLAMACION",
    },
    "895": {
        "nombre": "Envía documentación solicitud comisión Factura (ad..." if len("Envía documentación solicitud comisión Factura (adicional) (descripción que aplica al convenio 2010T") > 50 else "Envía documentación solicitud comisión Factura (adicional) (descripción que aplica al convenio 2010T",
        "descripcion": "Envía documentación solicitud comisión Factura (adicional) (descripción que aplica al convenio 2010T",
        "emisor": "HOSPITAL",
        "tipo": "RECLAMACION",
    },
    "896": {
        "nombre": "Documentación subcomisión/comisión..." if len("Documentación subcomisión/comisión") > 50 else "Documentación subcomisión/comisión",
        "descripcion": "Documentación subcomisión/comisión",
        "emisor": "DESCONOCIDO",
        "tipo": "RECLAMACION",
    },
    "897": {
        "nombre": "Documentación adicional tras petición subcomisión/..." if len("Documentación adicional tras petición subcomisión/comisión") > 50 else "Documentación adicional tras petición subcomisión/comisión",
        "descripcion": "Documentación adicional tras petición subcomisión/comisión",
        "emisor": "DESCONOCIDO",
        "tipo": "RECLAMACION",
    },
    "898": {
        "nombre": "Envía documentación solicitud comisión (adicional)..." if len("Envía documentación solicitud comisión (adicional) (descripción que aplica al convenio 2010T)") > 50 else "Envía documentación solicitud comisión (adicional) (descripción que aplica al convenio 2010T)",
        "descripcion": "Envía documentación solicitud comisión (adicional) (descripción que aplica al convenio 2010T)",
        "emisor": "ASEGURADORA",
        "tipo": "RECLAMACION",
    },
    "899": {
        "nombre": "Envía documentación solicitud subcomisión Factura ..." if len("Envía documentación solicitud subcomisión Factura (adicional) (sólo aplica al convenio 2010T)") > 50 else "Envía documentación solicitud subcomisión Factura (adicional) (sólo aplica al convenio 2010T)",
        "descripcion": "Envía documentación solicitud subcomisión Factura (adicional) (sólo aplica al convenio 2010T)",
        "emisor": "ASEGURADORA",
        "tipo": "RECLAMACION",
    },
}