ALL_CAS_CODES = {
    "101": {
        "nombre": "PA 368 FACTURA 662 PA..." if len("PA 368 FACTURA 662 PA") > 60 else "PA 368 FACTURA 662 PA",
        "descripcion": "PA 368 FACTURA 662 PA",
        "emisor": "DESCONOCIDO",
        "tipo": "INICIO",
    },
    "102": {
        "nombre": "PA urgencias modificado CH EA..." if len("PA urgencias modificado CH EA") > 60 else "PA urgencias modificado CH EA",
        "descripcion": "PA urgencias modificado CH EA",
        "emisor": "DESCONOCIDO",
        "tipo": "INICIO",
    },
    "170": {
        "nombre": "Parte de comunicación de lesiones CS EA..." if len("Parte de comunicación de lesiones CS EA") > 60 else "Parte de comunicación de lesiones CS EA",
        "descripcion": "Parte de comunicación de lesiones CS EA",
        "emisor": "DESCONOCIDO",
        "tipo": "INICIO",
    },
    "171": {
        "nombre": "Parte de primera Asistencia ambulatoria u hospitalaria. (des..." if len("Parte de primera Asistencia ambulatoria u hospitalaria. (descripción") > 60 else "Parte de primera Asistencia ambulatoria u hospitalaria. (descripción",
        "descripcion": "Parte de primera Asistencia ambulatoria u hospitalaria. (descripción",
        "emisor": "DESCONOCIDO",
        "tipo": "INICIO",
    },
    "172": {
        "nombre": "PA ambulatorio modificado (descripción que aplica al conveni..." if len("PA ambulatorio modificado (descripción que aplica al convenio 2010T") > 60 else "PA ambulatorio modificado (descripción que aplica al convenio 2010T",
        "descripcion": "PA ambulatorio modificado (descripción que aplica al convenio 2010T",
        "emisor": "DESCONOCIDO",
        "tipo": "INICIO",
    },
    "173": {
        "nombre": "PA reingreso/PA continuación gestión lesionado. (descripción..." if len("PA reingreso/PA continuación gestión lesionado. (descripción que") > 60 else "PA reingreso/PA continuación gestión lesionado. (descripción que",
        "descripcion": "PA reingreso/PA continuación gestión lesionado. (descripción que",
        "emisor": "DESCONOCIDO",
        "tipo": "INICIO",
    },
    "174": {
        "nombre": "Envía parte de asistencia de reingreso modificado. CH EA..." if len("Envía parte de asistencia de reingreso modificado. CH EA") > 60 else "Envía parte de asistencia de reingreso modificado. CH EA",
        "descripcion": "Envía parte de asistencia de reingreso modificado. CH EA",
        "emisor": "DESCONOCIDO",
        "tipo": "INICIO",
    },
    "175": {
        "nombre": "Envío parte de asistencia informativo CH/CS EA..." if len("Envío parte de asistencia informativo CH/CS EA") > 60 else "Envío parte de asistencia informativo CH/CS EA",
        "descripcion": "Envío parte de asistencia informativo CH/CS EA",
        "emisor": "DESCONOCIDO",
        "tipo": "INICIO",
    },
    "176": {
        "nombre": "Envío parte de asistencia de entidad no adherida a convenio ..." if len("Envío parte de asistencia de entidad no adherida a convenio CH EA") > 60 else "Envío parte de asistencia de entidad no adherida a convenio CH EA",
        "descripcion": "Envío parte de asistencia de entidad no adherida a convenio CH EA",
        "emisor": "DESCONOCIDO",
        "tipo": "INICIO",
    },
    "181": {
        "nombre": "FACTURA 394 RESTO 702 RESTO..." if len("FACTURA 394 RESTO 702 RESTO") > 60 else "FACTURA 394 RESTO 702 RESTO",
        "descripcion": "FACTURA 394 RESTO 702 RESTO",
        "emisor": "DESCONOCIDO",
        "tipo": "INICIO",
    },
    "191": {
        "nombre": "Envío parte de traslado interhospitalario. CH EA..." if len("Envío parte de traslado interhospitalario. CH EA") > 60 else "Envío parte de traslado interhospitalario. CH EA",
        "descripcion": "Envío parte de traslado interhospitalario. CH EA",
        "emisor": "DESCONOCIDO",
        "tipo": "INICIO",
    },
    "192": {
        "nombre": "Envío nuevo parte de traslado interhospitalario modificado C..." if len("Envío nuevo parte de traslado interhospitalario modificado CH EA") > 60 else "Envío nuevo parte de traslado interhospitalario modificado CH EA",
        "descripcion": "Envío nuevo parte de traslado interhospitalario modificado CH EA",
        "emisor": "DESCONOCIDO",
        "tipo": "INICIO",
    },
    "201": {
        "nombre": "Acepta parte de urgencias EA CH..." if len("Acepta parte de urgencias EA CH") > 60 else "Acepta parte de urgencias EA CH",
        "descripcion": "Acepta parte de urgencias EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "RESPUESTA",
    },
    "202": {
        "nombre": "Acepta continuación tratamiento EA CH..." if len("Acepta continuación tratamiento EA CH") > 60 else "Acepta continuación tratamiento EA CH",
        "descripcion": "Acepta continuación tratamiento EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "RESPUESTA",
    },
    "203": {
        "nombre": "Acepta lesionado alta especialización EA CH..." if len("Acepta lesionado alta especialización EA CH") > 60 else "Acepta lesionado alta especialización EA CH",
        "descripcion": "Acepta lesionado alta especialización EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "RESPUESTA",
    },
    "270": {
        "nombre": "Subcomisión acepta parte CS EA/CH..." if len("Subcomisión acepta parte CS EA/CH") > 60 else "Subcomisión acepta parte CS EA/CH",
        "descripcion": "Subcomisión acepta parte CS EA/CH",
        "emisor": "DESCONOCIDO",
        "tipo": "RESPUESTA",
    },
    "271": {
        "nombre": "Acepta el parte de asistencia. EA CH..." if len("Acepta el parte de asistencia. EA CH") > 60 else "Acepta el parte de asistencia. EA CH",
        "descripcion": "Acepta el parte de asistencia. EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "RESPUESTA",
    },
    "272": {
        "nombre": "Comisión acepta parte CS EA/CH..." if len("Comisión acepta parte CS EA/CH") > 60 else "Comisión acepta parte CS EA/CH",
        "descripcion": "Comisión acepta parte CS EA/CH",
        "emisor": "DESCONOCIDO",
        "tipo": "RESPUESTA",
    },
    "275": {
        "nombre": "Subcomision acepta parte tras recurso CS EA/CH..." if len("Subcomision acepta parte tras recurso CS EA/CH") > 60 else "Subcomision acepta parte tras recurso CS EA/CH",
        "descripcion": "Subcomision acepta parte tras recurso CS EA/CH",
        "emisor": "DESCONOCIDO",
        "tipo": "RESPUESTA",
    },
    "280": {
        "nombre": "Subcomisión acepta factura CS EA/CH..." if len("Subcomisión acepta factura CS EA/CH") > 60 else "Subcomisión acepta factura CS EA/CH",
        "descripcion": "Subcomisión acepta factura CS EA/CH",
        "emisor": "DESCONOCIDO",
        "tipo": "RESPUESTA",
    },
    "281": {
        "nombre": "Acepta la factura. EA CH..." if len("Acepta la factura. EA CH") > 60 else "Acepta la factura. EA CH",
        "descripcion": "Acepta la factura. EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "RESPUESTA",
    },
    "284": {
        "nombre": "Comisión acepta factura CS EA/CH..." if len("Comisión acepta factura CS EA/CH") > 60 else "Comisión acepta factura CS EA/CH",
        "descripcion": "Comisión acepta factura CS EA/CH",
        "emisor": "DESCONOCIDO",
        "tipo": "RESPUESTA",
    },
    "285": {
        "nombre": "Comisión acepta pago CS EA/CH..." if len("Comisión acepta pago CS EA/CH") > 60 else "Comisión acepta pago CS EA/CH",
        "descripcion": "Comisión acepta pago CS EA/CH",
        "emisor": "DESCONOCIDO",
        "tipo": "RESPUESTA",
    },
    "287": {
        "nombre": "Subcomisión acepta pago total CS EA/CH..." if len("Subcomisión acepta pago total CS EA/CH") > 60 else "Subcomisión acepta pago total CS EA/CH",
        "descripcion": "Subcomisión acepta pago total CS EA/CH",
        "emisor": "DESCONOCIDO",
        "tipo": "RESPUESTA",
    },
    "288": {
        "nombre": "Subcomisión acepta factura tras recurso CS EA/CH..." if len("Subcomisión acepta factura tras recurso CS EA/CH") > 60 else "Subcomisión acepta factura tras recurso CS EA/CH",
        "descripcion": "Subcomisión acepta factura tras recurso CS EA/CH",
        "emisor": "DESCONOCIDO",
        "tipo": "RESPUESTA",
    },
    "301": {
        "nombre": "Comunica Continuación tratamiento CH EA..." if len("Comunica Continuación tratamiento CH EA") > 60 else "Comunica Continuación tratamiento CH EA",
        "descripcion": "Comunica Continuación tratamiento CH EA",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "302": {
        "nombre": "Comunica cambio de diagnóstico CH EA..." if len("Comunica cambio de diagnóstico CH EA") > 60 else "Comunica cambio de diagnóstico CH EA",
        "descripcion": "Comunica cambio de diagnóstico CH EA",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "303": {
        "nombre": "Acepta cambio de diagnóstico EA CH..." if len("Acepta cambio de diagnóstico EA CH") > 60 else "Acepta cambio de diagnóstico EA CH",
        "descripcion": "Acepta cambio de diagnóstico EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "304": {
        "nombre": "Rechaza cambio de diagnóstico EA CH..." if len("Rechaza cambio de diagnóstico EA CH") > 60 else "Rechaza cambio de diagnóstico EA CH",
        "descripcion": "Rechaza cambio de diagnóstico EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "305": {
        "nombre": "Solicita aclaraciones cambio de diagnóstico EA CH..." if len("Solicita aclaraciones cambio de diagnóstico EA CH") > 60 else "Solicita aclaraciones cambio de diagnóstico EA CH",
        "descripcion": "Solicita aclaraciones cambio de diagnóstico EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "306": {
        "nombre": "Envía aclaraciones cambio diagnóstico CH CH..." if len("Envía aclaraciones cambio diagnóstico CH CH") > 60 else "Envía aclaraciones cambio diagnóstico CH CH",
        "descripcion": "Envía aclaraciones cambio diagnóstico CH CH",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "307": {
        "nombre": "Abierto plazo..." if len("Abierto plazo") > 60 else "Abierto plazo",
        "descripcion": "Abierto plazo",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "308": {
        "nombre": "FACTURA 487 FACTURA 824 DOCUMENTOS..." if len("FACTURA 487 FACTURA 824 DOCUMENTOS") > 60 else "FACTURA 487 FACTURA 824 DOCUMENTOS",
        "descripcion": "FACTURA 487 FACTURA 824 DOCUMENTOS",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "309": {
        "nombre": "No acepta rechazo de factura CH CH..." if len("No acepta rechazo de factura CH CH") > 60 else "No acepta rechazo de factura CH CH",
        "descripcion": "No acepta rechazo de factura CH CH",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "310": {
        "nombre": "Vencido plazo subcomisión CS CH..." if len("Vencido plazo subcomisión CS CH") > 60 else "Vencido plazo subcomisión CS CH",
        "descripcion": "Vencido plazo subcomisión CS CH",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "311": {
        "nombre": "Solicita informe médico de evolución EA CH..." if len("Solicita informe médico de evolución EA CH") > 60 else "Solicita informe médico de evolución EA CH",
        "descripcion": "Solicita informe médico de evolución EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "312": {
        "nombre": "Pendiente Informe de alta de urgencias CS CH..." if len("Pendiente Informe de alta de urgencias CS CH") > 60 else "Pendiente Informe de alta de urgencias CS CH",
        "descripcion": "Pendiente Informe de alta de urgencias CS CH",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "313": {
        "nombre": "Vencido plazo subcomisión factura CS CH..." if len("Vencido plazo subcomisión factura CS CH") > 60 else "Vencido plazo subcomisión factura CS CH",
        "descripcion": "Vencido plazo subcomisión factura CS CH",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "314": {
        "nombre": "Solicita envío hoja de firmas EA CH..." if len("Solicita envío hoja de firmas EA CH") > 60 else "Solicita envío hoja de firmas EA CH",
        "descripcion": "Solicita envío hoja de firmas EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "315": {
        "nombre": "Solicito autorización pruebas diagnósticas CH EA..." if len("Solicito autorización pruebas diagnósticas CH EA") > 60 else "Solicito autorización pruebas diagnósticas CH EA",
        "descripcion": "Solicito autorización pruebas diagnósticas CH EA",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "316": {
        "nombre": "Autorizo pruebas diagnósticas EA CH..." if len("Autorizo pruebas diagnósticas EA CH") > 60 else "Autorizo pruebas diagnósticas EA CH",
        "descripcion": "Autorizo pruebas diagnósticas EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "317": {
        "nombre": "No autorizo pruebas diagnósticas EA CH..." if len("No autorizo pruebas diagnósticas EA CH") > 60 else "No autorizo pruebas diagnósticas EA CH",
        "descripcion": "No autorizo pruebas diagnósticas EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "318": {
        "nombre": "RESTO 570 FACTURA 881 DOCUMENTOS..." if len("RESTO 570 FACTURA 881 DOCUMENTOS") > 60 else "RESTO 570 FACTURA 881 DOCUMENTOS",
        "descripcion": "RESTO 570 FACTURA 881 DOCUMENTOS",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "319": {
        "nombre": "Acepto Infiltraciones-bloqueos facetarios, nerviosos. EA CH..." if len("Acepto Infiltraciones-bloqueos facetarios, nerviosos. EA CH") > 60 else "Acepto Infiltraciones-bloqueos facetarios, nerviosos. EA CH",
        "descripcion": "Acepto Infiltraciones-bloqueos facetarios, nerviosos. EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "320": {
        "nombre": "Rechazo Infiltraciones-bloqueos facetarios, nerviosos. EA CH..." if len("Rechazo Infiltraciones-bloqueos facetarios, nerviosos. EA CH") > 60 else "Rechazo Infiltraciones-bloqueos facetarios, nerviosos. EA CH",
        "descripcion": "Rechazo Infiltraciones-bloqueos facetarios, nerviosos. EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "321": {
        "nombre": "Acepto ondas de choque radiales. EA CH..." if len("Acepto ondas de choque radiales. EA CH") > 60 else "Acepto ondas de choque radiales. EA CH",
        "descripcion": "Acepto ondas de choque radiales. EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "322": {
        "nombre": "Rechazo ondas de choque radiales. EA CH..." if len("Rechazo ondas de choque radiales. EA CH") > 60 else "Rechazo ondas de choque radiales. EA CH",
        "descripcion": "Rechazo ondas de choque radiales. EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "323": {
        "nombre": "Acepto ondas de choque focales. EA CH..." if len("Acepto ondas de choque focales. EA CH") > 60 else "Acepto ondas de choque focales. EA CH",
        "descripcion": "Acepto ondas de choque focales. EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "324": {
        "nombre": "Rechazo ondas de choque focales. EA CH..." if len("Rechazo ondas de choque focales. EA CH") > 60 else "Rechazo ondas de choque focales. EA CH",
        "descripcion": "Rechazo ondas de choque focales. EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "325": {
        "nombre": "Procede reducción de tarifas CS CH..." if len("Procede reducción de tarifas CS CH") > 60 else "Procede reducción de tarifas CS CH",
        "descripcion": "Procede reducción de tarifas CS CH",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "326": {
        "nombre": "Subcomisión resuelve que procede el cambio de diagnóstico. C..." if len("Subcomisión resuelve que procede el cambio de diagnóstico. CS CH") > 60 else "Subcomisión resuelve que procede el cambio de diagnóstico. CS CH",
        "descripcion": "Subcomisión resuelve que procede el cambio de diagnóstico. CS CH",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "327": {
        "nombre": "Subcomisión resuelve que no procede el cambio de diagnóstico..." if len("Subcomisión resuelve que no procede el cambio de diagnóstico. CS CH") > 60 else "Subcomisión resuelve que no procede el cambio de diagnóstico. CS CH",
        "descripcion": "Subcomisión resuelve que no procede el cambio de diagnóstico. CS CH",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "360": {
        "nombre": "Cambio de referencia del expediente EA CH..." if len("Cambio de referencia del expediente EA CH") > 60 else "Cambio de referencia del expediente EA CH",
        "descripcion": "Cambio de referencia del expediente EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "361": {
        "nombre": "EA solicita módulo reducido EA CH..." if len("EA solicita módulo reducido EA CH") > 60 else "EA solicita módulo reducido EA CH",
        "descripcion": "EA solicita módulo reducido EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "362": {
        "nombre": "Solicita información aclaratoria. EA CH..." if len("Solicita información aclaratoria. EA CH") > 60 else "Solicita información aclaratoria. EA CH",
        "descripcion": "Solicita información aclaratoria. EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "363": {
        "nombre": "Envía información aclaratoria. CH EA..." if len("Envía información aclaratoria. CH EA") > 60 else "Envía información aclaratoria. CH EA",
        "descripcion": "Envía información aclaratoria. CH EA",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "364": {
        "nombre": "CS confirma aplica módulo reducido CH EA..." if len("CS confirma aplica módulo reducido CH EA") > 60 else "CS confirma aplica módulo reducido CH EA",
        "descripcion": "CS confirma aplica módulo reducido CH EA",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "365": {
        "nombre": "Justificación de envío fuera de plazo. CH EA..." if len("Justificación de envío fuera de plazo. CH EA") > 60 else "Justificación de envío fuera de plazo. CH EA",
        "descripcion": "Justificación de envío fuera de plazo. CH EA",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "366": {
        "nombre": "Documentación sin catalogar. CH EA..." if len("Documentación sin catalogar. CH EA") > 60 else "Documentación sin catalogar. CH EA",
        "descripcion": "Documentación sin catalogar. CH EA",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "367": {
        "nombre": "Documentación sin catalogar EA CH..." if len("Documentación sin catalogar EA CH") > 60 else "Documentación sin catalogar EA CH",
        "descripcion": "Documentación sin catalogar EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "368": {
        "nombre": "Solicita aclaración factura EA CH..." if len("Solicita aclaración factura EA CH") > 60 else "Solicita aclaración factura EA CH",
        "descripcion": "Solicita aclaración factura EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "369": {
        "nombre": "Envía aclaración factura. CH EA..." if len("Envía aclaración factura. CH EA") > 60 else "Envía aclaración factura. CH EA",
        "descripcion": "Envía aclaración factura. CH EA",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "370": {
        "nombre": "Solicita autorización inicio tratamiento rehabilitador fuera..." if len("Solicita autorización inicio tratamiento rehabilitador fuera termino") > 60 else "Solicita autorización inicio tratamiento rehabilitador fuera termino",
        "descripcion": "Solicita autorización inicio tratamiento rehabilitador fuera termino",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "371": {
        "nombre": "Autoriza tratamiento rehabilitador fuera del término municip..." if len("Autoriza tratamiento rehabilitador fuera del término municipal EA CH") > 60 else "Autoriza tratamiento rehabilitador fuera del término municipal EA CH",
        "descripcion": "Autoriza tratamiento rehabilitador fuera del término municipal EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "372": {
        "nombre": "No autoriza tratamiento rehabilitador fuera del término muni..." if len("No autoriza tratamiento rehabilitador fuera del término municipal EA CH") > 60 else "No autoriza tratamiento rehabilitador fuera del término municipal EA CH",
        "descripcion": "No autoriza tratamiento rehabilitador fuera del término municipal EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "373": {
        "nombre": "CS rechaza aplicar módulo reducido CH EA..." if len("CS rechaza aplicar módulo reducido CH EA") > 60 else "CS rechaza aplicar módulo reducido CH EA",
        "descripcion": "CS rechaza aplicar módulo reducido CH EA",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "374": {
        "nombre": "Justificante de no aseguramiento. EA CH..." if len("Justificante de no aseguramiento. EA CH") > 60 else "Justificante de no aseguramiento. EA CH",
        "descripcion": "Justificante de no aseguramiento. EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "375": {
        "nombre": "Solicita aclaración declaración responsable CCS CH..." if len("Solicita aclaración declaración responsable CCS CH") > 60 else "Solicita aclaración declaración responsable CCS CH",
        "descripcion": "Solicita aclaración declaración responsable CCS CH",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "376": {
        "nombre": "Envía aclaración declaración responsable CH CCS..." if len("Envía aclaración declaración responsable CH CCS") > 60 else "Envía aclaración declaración responsable CH CCS",
        "descripcion": "Envía aclaración declaración responsable CH CCS",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "377": {
        "nombre": "Envía información alegaciones parte CH EA..." if len("Envía información alegaciones parte CH EA") > 60 else "Envía información alegaciones parte CH EA",
        "descripcion": "Envía información alegaciones parte CH EA",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "378": {
        "nombre": "Envía información alegaciones parte EA CH..." if len("Envía información alegaciones parte EA CH") > 60 else "Envía información alegaciones parte EA CH",
        "descripcion": "Envía información alegaciones parte EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "379": {
        "nombre": "Envía información alegaciones factura CH EA..." if len("Envía información alegaciones factura CH EA") > 60 else "Envía información alegaciones factura CH EA",
        "descripcion": "Envía información alegaciones factura CH EA",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "380": {
        "nombre": "Envía información alegaciones factura EA CH..." if len("Envía información alegaciones factura EA CH") > 60 else "Envía información alegaciones factura EA CH",
        "descripcion": "Envía información alegaciones factura EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "381": {
        "nombre": "Entidad notifica pago de la factura EA/CS CH..." if len("Entidad notifica pago de la factura EA/CS CH") > 60 else "Entidad notifica pago de la factura EA/CS CH",
        "descripcion": "Entidad notifica pago de la factura EA/CS CH",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "382": {
        "nombre": "Pago parcial..." if len("Pago parcial") > 60 else "Pago parcial",
        "descripcion": "Pago parcial",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "383": {
        "nombre": "EA diálogo adicional aplicación módulo EA CH..." if len("EA diálogo adicional aplicación módulo EA CH") > 60 else "EA diálogo adicional aplicación módulo EA CH",
        "descripcion": "EA diálogo adicional aplicación módulo EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "384": {
        "nombre": "CS diálogo adicional aplicación módulo CH EA..." if len("CS diálogo adicional aplicación módulo CH EA") > 60 else "CS diálogo adicional aplicación módulo CH EA",
        "descripcion": "CS diálogo adicional aplicación módulo CH EA",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "387": {
        "nombre": "EA comunica límite del conductor EA CH..." if len("EA comunica límite del conductor EA CH") > 60 else "EA comunica límite del conductor EA CH",
        "descripcion": "EA comunica límite del conductor EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "390": {
        "nombre": "EA envía aclaraciones Parte Asistencia, solicitud subcomisió..." if len("EA envía aclaraciones Parte Asistencia, solicitud subcomisión EA CS") > 60 else "EA envía aclaraciones Parte Asistencia, solicitud subcomisión EA CS",
        "descripcion": "EA envía aclaraciones Parte Asistencia, solicitud subcomisión EA CS",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "391": {
        "nombre": "CH envía aclaraciones Parte Asistencia, solicitud subcomisió..." if len("CH envía aclaraciones Parte Asistencia, solicitud subcomisión CH CS") > 60 else "CH envía aclaraciones Parte Asistencia, solicitud subcomisión CH CS",
        "descripcion": "CH envía aclaraciones Parte Asistencia, solicitud subcomisión CH CS",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "392": {
        "nombre": "CH envía aclaraciones Parte Asistencia, solicitud Comisión C..." if len("CH envía aclaraciones Parte Asistencia, solicitud Comisión CH CS") > 60 else "CH envía aclaraciones Parte Asistencia, solicitud Comisión CH CS",
        "descripcion": "CH envía aclaraciones Parte Asistencia, solicitud Comisión CH CS",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "393": {
        "nombre": "CS envía aclaraciones solicitud subcomisión (adicional)..." if len("CS envía aclaraciones solicitud subcomisión (adicional)") > 60 else "CS envía aclaraciones solicitud subcomisión (adicional)",
        "descripcion": "CS envía aclaraciones solicitud subcomisión (adicional)",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "394": {
        "nombre": "EA envía aclaraciones Factura, solicitud Comisión EA CS..." if len("EA envía aclaraciones Factura, solicitud Comisión EA CS") > 60 else "EA envía aclaraciones Factura, solicitud Comisión EA CS",
        "descripcion": "EA envía aclaraciones Factura, solicitud Comisión EA CS",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "395": {
        "nombre": "CH envía aclaraciones Factura, solicitud Comisión CH CS..." if len("CH envía aclaraciones Factura, solicitud Comisión CH CS") > 60 else "CH envía aclaraciones Factura, solicitud Comisión CH CS",
        "descripcion": "CH envía aclaraciones Factura, solicitud Comisión CH CS",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "398": {
        "nombre": "EA envía aclaraciones Parte Asistencia, solicitud Comisión E..." if len("EA envía aclaraciones Parte Asistencia, solicitud Comisión EA CS") > 60 else "EA envía aclaraciones Parte Asistencia, solicitud Comisión EA CS",
        "descripcion": "EA envía aclaraciones Parte Asistencia, solicitud Comisión EA CS",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "399": {
        "nombre": "EA envía aclaraciones Factura, solicitud Subcomisión EA CS..." if len("EA envía aclaraciones Factura, solicitud Subcomisión EA CS") > 60 else "EA envía aclaraciones Factura, solicitud Subcomisión EA CS",
        "descripcion": "EA envía aclaraciones Factura, solicitud Subcomisión EA CS",
        "emisor": "DESCONOCIDO",
        "tipo": "DOCUMENTACION",
    },
    "401": {
        "nombre": "Parte de urgencias no cumplimentado correctamente EA CH..." if len("Parte de urgencias no cumplimentado correctamente EA CH") > 60 else "Parte de urgencias no cumplimentado correctamente EA CH",
        "descripcion": "Parte de urgencias no cumplimentado correctamente EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "CONFIRMACION",
    },
    "403": {
        "nombre": "Rechaza lesionado alta especialización EA CH..." if len("Rechaza lesionado alta especialización EA CH") > 60 else "Rechaza lesionado alta especialización EA CH",
        "descripcion": "Rechaza lesionado alta especialización EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "CONFIRMACION",
    },
    "421": {
        "nombre": "Rechaza declaración responsable CCS CH..." if len("Rechaza declaración responsable CCS CH") > 60 else "Rechaza declaración responsable CCS CH",
        "descripcion": "Rechaza declaración responsable CCS CH",
        "emisor": "DESCONOCIDO",
        "tipo": "CONFIRMACION",
    },
    "422": {
        "nombre": "Rechaza parte, transcurrido plazo 72 h. (Traumatismo menor C..." if len("Rechaza parte, transcurrido plazo 72 h. (Traumatismo menor CV) EA CH") > 60 else "Rechaza parte, transcurrido plazo 72 h. (Traumatismo menor CV) EA CH",
        "descripcion": "Rechaza parte, transcurrido plazo 72 h. (Traumatismo menor CV) EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "CONFIRMACION",
    },
    "423": {
        "nombre": "Rechaza parte, lesionado no viaja en espacio destinado a per..." if len("Rechaza parte, lesionado no viaja en espacio destinado a personas EA CH") > 60 else "Rechaza parte, lesionado no viaja en espacio destinado a personas EA CH",
        "descripcion": "Rechaza parte, lesionado no viaja en espacio destinado a personas EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "CONFIRMACION",
    },
    "442": {
        "nombre": "Rechaza factura, transcurrido plazo 72 h. (Traumatismo menor..." if len("Rechaza factura, transcurrido plazo 72 h. (Traumatismo menor CV) EA CH") > 60 else "Rechaza factura, transcurrido plazo 72 h. (Traumatismo menor CV) EA CH",
        "descripcion": "Rechaza factura, transcurrido plazo 72 h. (Traumatismo menor CV) EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "CONFIRMACION",
    },
    "443": {
        "nombre": "Rechaza factura, Lesionado no en espacio destinado a persona..." if len("Rechaza factura, Lesionado no en espacio destinado a personas EA CH") > 60 else "Rechaza factura, Lesionado no en espacio destinado a personas EA CH",
        "descripcion": "Rechaza factura, Lesionado no en espacio destinado a personas EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "CONFIRMACION",
    },
    "471": {
        "nombre": "Rechazo del parte de asistencia. EA CH..." if len("Rechazo del parte de asistencia. EA CH") > 60 else "Rechazo del parte de asistencia. EA CH",
        "descripcion": "Rechazo del parte de asistencia. EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "CONFIRMACION",
    },
    "472": {
        "nombre": "Parte de asistencia no cumplimentado correctamente. EA CH..." if len("Parte de asistencia no cumplimentado correctamente. EA CH") > 60 else "Parte de asistencia no cumplimentado correctamente. EA CH",
        "descripcion": "Parte de asistencia no cumplimentado correctamente. EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "CONFIRMACION",
    },
    "473": {
        "nombre": "No hay acuerdo con el contenido del parte de asistencia. EA ..." if len("No hay acuerdo con el contenido del parte de asistencia. EA CH") > 60 else "No hay acuerdo con el contenido del parte de asistencia. EA CH",
        "descripcion": "No hay acuerdo con el contenido del parte de asistencia. EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "CONFIRMACION",
    },
    "474": {
        "nombre": "Rechaza el parte por no asegurar al vehículo. EA CH..." if len("Rechaza el parte por no asegurar al vehículo. EA CH") > 60 else "Rechaza el parte por no asegurar al vehículo. EA CH",
        "descripcion": "Rechaza el parte por no asegurar al vehículo. EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "CONFIRMACION",
    },
    "475": {
        "nombre": "No corresponde el pago (estipulación de Convenio). EA CH..." if len("No corresponde el pago (estipulación de Convenio). EA CH") > 60 else "No corresponde el pago (estipulación de Convenio). EA CH",
        "descripcion": "No corresponde el pago (estipulación de Convenio). EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "CONFIRMACION",
    },
    "476": {
        "nombre": "Rechaza parte, no corresponde pago entidad no adherida EA CH..." if len("Rechaza parte, no corresponde pago entidad no adherida EA CH") > 60 else "Rechaza parte, no corresponde pago entidad no adherida EA CH",
        "descripcion": "Rechaza parte, no corresponde pago entidad no adherida EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "CONFIRMACION",
    },
    "477": {
        "nombre": "Rechaza parte, conductor sin cobertura EA CH..." if len("Rechaza parte, conductor sin cobertura EA CH") > 60 else "Rechaza parte, conductor sin cobertura EA CH",
        "descripcion": "Rechaza parte, conductor sin cobertura EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "CONFIRMACION",
    },
    "478": {
        "nombre": "Rechaza por existir seguro CCS CH..." if len("Rechaza por existir seguro CCS CH") > 60 else "Rechaza por existir seguro CCS CH",
        "descripcion": "Rechaza por existir seguro CCS CH",
        "emisor": "DESCONOCIDO",
        "tipo": "CONFIRMACION",
    },
    "481": {
        "nombre": "Rechaza factura: asistencia posterior a comunicación no acep..." if len("Rechaza factura: asistencia posterior a comunicación no aceptación") > 60 else "Rechaza factura: asistencia posterior a comunicación no aceptación",
        "descripcion": "Rechaza factura: asistencia posterior a comunicación no aceptación",
        "emisor": "DESCONOCIDO",
        "tipo": "CONFIRMACION",
    },
    "482": {
        "nombre": "Rechaza factura por no asegurar el vehículo EA CH..." if len("Rechaza factura por no asegurar el vehículo EA CH") > 60 else "Rechaza factura por no asegurar el vehículo EA CH",
        "descripcion": "Rechaza factura por no asegurar el vehículo EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "CONFIRMACION",
    },
    "483": {
        "nombre": "Rechaza factura por no aplicar convenio EA CH..." if len("Rechaza factura por no aplicar convenio EA CH") > 60 else "Rechaza factura por no aplicar convenio EA CH",
        "descripcion": "Rechaza factura por no aplicar convenio EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "CONFIRMACION",
    },
    "484": {
        "nombre": "Rechaza factura por existir seguro   CCS CH..." if len("Rechaza factura por existir seguro   CCS CH") > 60 else "Rechaza factura por existir seguro   CCS CH",
        "descripcion": "Rechaza factura por existir seguro   CCS CH",
        "emisor": "DESCONOCIDO",
        "tipo": "CONFIRMACION",
    },
    "485": {
        "nombre": "Rechaza factura, no corresponde pago entidad no adherida  EA..." if len("Rechaza factura, no corresponde pago entidad no adherida  EA CH") > 60 else "Rechaza factura, no corresponde pago entidad no adherida  EA CH",
        "descripcion": "Rechaza factura, no corresponde pago entidad no adherida  EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "CONFIRMACION",
    },
    "486": {
        "nombre": "Rechazo factura, transcurso de los plazos previstos en el Co..." if len("Rechazo factura, transcurso de los plazos previstos en el Convenio EA CH") > 60 else "Rechazo factura, transcurso de los plazos previstos en el Convenio EA CH",
        "descripcion": "Rechazo factura, transcurso de los plazos previstos en el Convenio EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "CONFIRMACION",
    },
    "487": {
        "nombre": "Rechaza factura: discrepancia o desproporción entre diagnóst..." if len("Rechaza factura: discrepancia o desproporción entre diagnóstico y el") > 60 else "Rechaza factura: discrepancia o desproporción entre diagnóstico y el",
        "descripcion": "Rechaza factura: discrepancia o desproporción entre diagnóstico y el",
        "emisor": "DESCONOCIDO",
        "tipo": "CONFIRMACION",
    },
    "488": {
        "nombre": "Rechaza factura, prestación no autorizada EA CH..." if len("Rechaza factura, prestación no autorizada EA CH") > 60 else "Rechaza factura, prestación no autorizada EA CH",
        "descripcion": "Rechaza factura, prestación no autorizada EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "CONFIRMACION",
    },
    "492": {
        "nombre": "No se trata de un hecho de la circulación. EA CH..." if len("No se trata de un hecho de la circulación. EA CH") > 60 else "No se trata de un hecho de la circulación. EA CH",
        "descripcion": "No se trata de un hecho de la circulación. EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "CONFIRMACION",
    },
    "494": {
        "nombre": "Transcurso de los plazos previstos en el Convenio. EA CH..." if len("Transcurso de los plazos previstos en el Convenio. EA CH") > 60 else "Transcurso de los plazos previstos en el Convenio. EA CH",
        "descripcion": "Transcurso de los plazos previstos en el Convenio. EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "CONFIRMACION",
    },
    "495": {
        "nombre": "Existencia probada de fraude. EA CH..." if len("Existencia probada de fraude. EA CH") > 60 else "Existencia probada de fraude. EA CH",
        "descripcion": "Existencia probada de fraude. EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "CONFIRMACION",
    },
    "496": {
        "nombre": "Falta de relación causal, criterio cronológico. EA CH..." if len("Falta de relación causal, criterio cronológico. EA CH") > 60 else "Falta de relación causal, criterio cronológico. EA CH",
        "descripcion": "Falta de relación causal, criterio cronológico. EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "CONFIRMACION",
    },
    "497": {
        "nombre": "Falta de relación causal, criterio de intensidad. EA CH..." if len("Falta de relación causal, criterio de intensidad. EA CH") > 60 else "Falta de relación causal, criterio de intensidad. EA CH",
        "descripcion": "Falta de relación causal, criterio de intensidad. EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "CONFIRMACION",
    },
    "498": {
        "nombre": "Falta de relación causal, criterio topográfico. EA CH..." if len("Falta de relación causal, criterio topográfico. EA CH") > 60 else "Falta de relación causal, criterio topográfico. EA CH",
        "descripcion": "Falta de relación causal, criterio topográfico. EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "CONFIRMACION",
    },
    "499": {
        "nombre": "Falta de relación causal, criterio de exclusión. EA CH..." if len("Falta de relación causal, criterio de exclusión. EA CH") > 60 else "Falta de relación causal, criterio de exclusión. EA CH",
        "descripcion": "Falta de relación causal, criterio de exclusión. EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "CONFIRMACION",
    },
    "500": {
        "nombre": "Abandona gestión expediente CH EA..." if len("Abandona gestión expediente CH EA") > 60 else "Abandona gestión expediente CH EA",
        "descripcion": "Abandona gestión expediente CH EA",
        "emisor": "DESCONOCIDO",
        "tipo": "FACTURACION",
    },
    "501": {
        "nombre": "Baja de expediente con pago CH EA..." if len("Baja de expediente con pago CH EA") > 60 else "Baja de expediente con pago CH EA",
        "descripcion": "Baja de expediente con pago CH EA",
        "emisor": "DESCONOCIDO",
        "tipo": "FACTURACION",
    },
    "502": {
        "nombre": "Baja del expediente CS EA/CH..." if len("Baja del expediente CS EA/CH") > 60 else "Baja del expediente CS EA/CH",
        "descripcion": "Baja del expediente CS EA/CH",
        "emisor": "DESCONOCIDO",
        "tipo": "FACTURACION",
    },
    "503": {
        "nombre": "Acepta rechazo de parte  CS EA..." if len("Acepta rechazo de parte  CS EA") > 60 else "Acepta rechazo de parte  CS EA",
        "descripcion": "Acepta rechazo de parte  CS EA",
        "emisor": "DESCONOCIDO",
        "tipo": "FACTURACION",
    },
    "504": {
        "nombre": "Baja expediente no convenio. CH EA..." if len("Baja expediente no convenio. CH EA") > 60 else "Baja expediente no convenio. CH EA",
        "descripcion": "Baja expediente no convenio. CH EA",
        "emisor": "DESCONOCIDO",
        "tipo": "FACTURACION",
    },
    "570": {
        "nombre": "Abandona gestión de factura. CS EA..." if len("Abandona gestión de factura. CS EA") > 60 else "Abandona gestión de factura. CS EA",
        "descripcion": "Abandona gestión de factura. CS EA",
        "emisor": "DESCONOCIDO",
        "tipo": "FACTURACION",
    },
    "572": {
        "nombre": "Subcomisión No procede parte CS EA/CH..." if len("Subcomisión No procede parte CS EA/CH") > 60 else "Subcomisión No procede parte CS EA/CH",
        "descripcion": "Subcomisión No procede parte CS EA/CH",
        "emisor": "DESCONOCIDO",
        "tipo": "FACTURACION",
    },
    "573": {
        "nombre": "Subcomisión resuelve no procede factura (descripción que apl..." if len("Subcomisión resuelve no procede factura (descripción que aplica al") > 60 else "Subcomisión resuelve no procede factura (descripción que aplica al",
        "descripcion": "Subcomisión resuelve no procede factura (descripción que aplica al",
        "emisor": "DESCONOCIDO",
        "tipo": "FACTURACION",
    },
    "574": {
        "nombre": "Subcomisión no procede parte tras recurso CS EA/CH..." if len("Subcomisión no procede parte tras recurso CS EA/CH") > 60 else "Subcomisión no procede parte tras recurso CS EA/CH",
        "descripcion": "Subcomisión no procede parte tras recurso CS EA/CH",
        "emisor": "DESCONOCIDO",
        "tipo": "FACTURACION",
    },
    "575": {
        "nombre": "Comisión resuelve no procede parte CS EA/CH..." if len("Comisión resuelve no procede parte CS EA/CH") > 60 else "Comisión resuelve no procede parte CS EA/CH",
        "descripcion": "Comisión resuelve no procede parte CS EA/CH",
        "emisor": "DESCONOCIDO",
        "tipo": "FACTURACION",
    },
    "576": {
        "nombre": "Comisión resuelve no procede factura CS EA/CH..." if len("Comisión resuelve no procede factura CS EA/CH") > 60 else "Comisión resuelve no procede factura CS EA/CH",
        "descripcion": "Comisión resuelve no procede factura CS EA/CH",
        "emisor": "DESCONOCIDO",
        "tipo": "FACTURACION",
    },
    "577": {
        "nombre": "Subcomisión no procede factura tras recurso CS EA/CH..." if len("Subcomisión no procede factura tras recurso CS EA/CH") > 60 else "Subcomisión no procede factura tras recurso CS EA/CH",
        "descripcion": "Subcomisión no procede factura tras recurso CS EA/CH",
        "emisor": "DESCONOCIDO",
        "tipo": "FACTURACION",
    },
    "578": {
        "nombre": "Subcomisión resuelve no procede pago total CS EA/CH..." if len("Subcomisión resuelve no procede pago total CS EA/CH") > 60 else "Subcomisión resuelve no procede pago total CS EA/CH",
        "descripcion": "Subcomisión resuelve no procede pago total CS EA/CH",
        "emisor": "DESCONOCIDO",
        "tipo": "FACTURACION",
    },
    "579": {
        "nombre": "Comisión resuelve No procede total CS EA/CH..." if len("Comisión resuelve No procede total CS EA/CH") > 60 else "Comisión resuelve No procede total CS EA/CH",
        "descripcion": "Comisión resuelve No procede total CS EA/CH",
        "emisor": "DESCONOCIDO",
        "tipo": "FACTURACION",
    },
    "580": {
        "nombre": "Envía factura rectificativa de anulación CH EA..." if len("Envía factura rectificativa de anulación CH EA") > 60 else "Envía factura rectificativa de anulación CH EA",
        "descripcion": "Envía factura rectificativa de anulación CH EA",
        "emisor": "DESCONOCIDO",
        "tipo": "FACTURACION",
    },
    "581": {
        "nombre": "Confirma factura abonada totalmente CH EA..." if len("Confirma factura abonada totalmente CH EA") > 60 else "Confirma factura abonada totalmente CH EA",
        "descripcion": "Confirma factura abonada totalmente CH EA",
        "emisor": "DESCONOCIDO",
        "tipo": "FACTURACION",
    },
    "582": {
        "nombre": "Confirma factura abonada parcialmente CH EA..." if len("Confirma factura abonada parcialmente CH EA") > 60 else "Confirma factura abonada parcialmente CH EA",
        "descripcion": "Confirma factura abonada parcialmente CH EA",
        "emisor": "DESCONOCIDO",
        "tipo": "FACTURACION",
    },
    "583": {
        "nombre": "Factura sin abono por Convenio CS/CH EA..." if len("Factura sin abono por Convenio CS/CH EA") > 60 else "Factura sin abono por Convenio CS/CH EA",
        "descripcion": "Factura sin abono por Convenio CS/CH EA",
        "emisor": "DESCONOCIDO",
        "tipo": "FACTURACION",
    },
    "584": {
        "nombre": "Cierre factura. No procede. CS EA/CH..." if len("Cierre factura. No procede. CS EA/CH") > 60 else "Cierre factura. No procede. CS EA/CH",
        "descripcion": "Cierre factura. No procede. CS EA/CH",
        "emisor": "DESCONOCIDO",
        "tipo": "FACTURACION",
    },
    "585": {
        "nombre": "Envía factura rectificativa de importes CH EA..." if len("Envía factura rectificativa de importes CH EA") > 60 else "Envía factura rectificativa de importes CH EA",
        "descripcion": "Envía factura rectificativa de importes CH EA",
        "emisor": "DESCONOCIDO",
        "tipo": "FACTURACION",
    },
    "586": {
        "nombre": "Cierre factura. No procede total CS EA/CH..." if len("Cierre factura. No procede total CS EA/CH") > 60 else "Cierre factura. No procede total CS EA/CH",
        "descripcion": "Cierre factura. No procede total CS EA/CH",
        "emisor": "DESCONOCIDO",
        "tipo": "FACTURACION",
    },
    "587": {
        "nombre": "Cierre factura con embargo CH EA..." if len("Cierre factura con embargo CH EA") > 60 else "Cierre factura con embargo CH EA",
        "descripcion": "Cierre factura con embargo CH EA",
        "emisor": "DESCONOCIDO",
        "tipo": "FACTURACION",
    },
    "652": {
        "nombre": "Alegaciones Subcomisión parte EA/CH EA/CH..." if len("Alegaciones Subcomisión parte EA/CH EA/CH") > 60 else "Alegaciones Subcomisión parte EA/CH EA/CH",
        "descripcion": "Alegaciones Subcomisión parte EA/CH EA/CH",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "653": {
        "nombre": "Alegaciones Subcomisión factura EA/CH EA/CH..." if len("Alegaciones Subcomisión factura EA/CH EA/CH") > 60 else "Alegaciones Subcomisión factura EA/CH EA/CH",
        "descripcion": "Alegaciones Subcomisión factura EA/CH EA/CH",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "655": {
        "nombre": "Alegaciones subcomisión cambio de diagnóstico (2010U) CS EA..." if len("Alegaciones subcomisión cambio de diagnóstico (2010U) CS EA") > 60 else "Alegaciones subcomisión cambio de diagnóstico (2010U) CS EA",
        "descripcion": "Alegaciones subcomisión cambio de diagnóstico (2010U) CS EA",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "662": {
        "nombre": "Subcomisión automatizada por Parte CS EA/CH..." if len("Subcomisión automatizada por Parte CS EA/CH") > 60 else "Subcomisión automatizada por Parte CS EA/CH",
        "descripcion": "Subcomisión automatizada por Parte CS EA/CH",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "663": {
        "nombre": "Subcomisión automatizada por Factura CS EA/CH..." if len("Subcomisión automatizada por Factura CS EA/CH") > 60 else "Subcomisión automatizada por Factura CS EA/CH",
        "descripcion": "Subcomisión automatizada por Factura CS EA/CH",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "664": {
        "nombre": "Envío a subcomisión disconformidad reducción tarifa CH EA/CH..." if len("Envío a subcomisión disconformidad reducción tarifa CH EA/CH") > 60 else "Envío a subcomisión disconformidad reducción tarifa CH EA/CH",
        "descripcion": "Envío a subcomisión disconformidad reducción tarifa CH EA/CH",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "665": {
        "nombre": "Subcomision automatizada por cambio de diagnóstico (2010U) C..." if len("Subcomision automatizada por cambio de diagnóstico (2010U) CH EA/CH") > 60 else "Subcomision automatizada por cambio de diagnóstico (2010U) CH EA/CH",
        "descripcion": "Subcomision automatizada por cambio de diagnóstico (2010U) CH EA/CH",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "666": {
        "nombre": "PA elevado a Comisión CS EA/CH..." if len("PA elevado a Comisión CS EA/CH") > 60 else "PA elevado a Comisión CS EA/CH",
        "descripcion": "PA elevado a Comisión CS EA/CH",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "667": {
        "nombre": "Factura elevada a Comisión CS EA/CH..." if len("Factura elevada a Comisión CS EA/CH") > 60 else "Factura elevada a Comisión CS EA/CH",
        "descripcion": "Factura elevada a Comisión CS EA/CH",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "669": {
        "nombre": "Subcomisión solicita documentación aclaración parte CS EA/CH..." if len("Subcomisión solicita documentación aclaración parte CS EA/CH") > 60 else "Subcomisión solicita documentación aclaración parte CS EA/CH",
        "descripcion": "Subcomisión solicita documentación aclaración parte CS EA/CH",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "670": {
        "nombre": "Interlocutores por Parte CH/EA EA/CH..." if len("Interlocutores por Parte CH/EA EA/CH") > 60 else "Interlocutores por Parte CH/EA EA/CH",
        "descripcion": "Interlocutores por Parte CH/EA EA/CH",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "671": {
        "nombre": "Interlocutores por Factura CH/EA EA/CH..." if len("Interlocutores por Factura CH/EA EA/CH") > 60 else "Interlocutores por Factura CH/EA EA/CH",
        "descripcion": "Interlocutores por Factura CH/EA EA/CH",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "672": {
        "nombre": "Fin gestión Parte en CAS. Gestionar con subcomisión no autom..." if len("Fin gestión Parte en CAS. Gestionar con subcomisión no automatizada CS EA/CH") > 60 else "Fin gestión Parte en CAS. Gestionar con subcomisión no automatizada CS EA/CH",
        "descripcion": "Fin gestión Parte en CAS. Gestionar con subcomisión no automatizada CS EA/CH",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "673": {
        "nombre": "Fin gestión Factura en CAS. Gestionar con subcomisión no..." if len("Fin gestión Factura en CAS. Gestionar con subcomisión no") > 60 else "Fin gestión Factura en CAS. Gestionar con subcomisión no",
        "descripcion": "Fin gestión Factura en CAS. Gestionar con subcomisión no",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "674": {
        "nombre": "Subcomisión por falta de pago CS EA/CH..." if len("Subcomisión por falta de pago CS EA/CH") > 60 else "Subcomisión por falta de pago CS EA/CH",
        "descripcion": "Subcomisión por falta de pago CS EA/CH",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "676": {
        "nombre": "CCS Pago pendiente CS EA/CH..." if len("CCS Pago pendiente CS EA/CH") > 60 else "CCS Pago pendiente CS EA/CH",
        "descripcion": "CCS Pago pendiente CS EA/CH",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "677": {
        "nombre": "Comisión solicita documentación aclaración Parte Asistencia..." if len("Comisión solicita documentación aclaración Parte Asistencia") > 60 else "Comisión solicita documentación aclaración Parte Asistencia",
        "descripcion": "Comisión solicita documentación aclaración Parte Asistencia",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "678": {
        "nombre": "Subcomisión solicita documentación aclaración Factura CS EA/..." if len("Subcomisión solicita documentación aclaración Factura CS EA/CH") > 60 else "Subcomisión solicita documentación aclaración Factura CS EA/CH",
        "descripcion": "Subcomisión solicita documentación aclaración Factura CS EA/CH",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "679": {
        "nombre": "Comisión solicita documentación aclaración Factura CS EA/CH..." if len("Comisión solicita documentación aclaración Factura CS EA/CH") > 60 else "Comisión solicita documentación aclaración Factura CS EA/CH",
        "descripcion": "Comisión solicita documentación aclaración Factura CS EA/CH",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "680": {
        "nombre": "Recurre resolución subcomisión parte..." if len("Recurre resolución subcomisión parte") > 60 else "Recurre resolución subcomisión parte",
        "descripcion": "Recurre resolución subcomisión parte",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "681": {
        "nombre": "Recurre resolución subcomisión parte..." if len("Recurre resolución subcomisión parte") > 60 else "Recurre resolución subcomisión parte",
        "descripcion": "Recurre resolución subcomisión parte",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "682": {
        "nombre": "Resolución firme subcomisión acepta parte CS EA/CH..." if len("Resolución firme subcomisión acepta parte CS EA/CH") > 60 else "Resolución firme subcomisión acepta parte CS EA/CH",
        "descripcion": "Resolución firme subcomisión acepta parte CS EA/CH",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "683": {
        "nombre": "Resolución firme subcomisión no procede parte CS EA/CH..." if len("Resolución firme subcomisión no procede parte CS EA/CH") > 60 else "Resolución firme subcomisión no procede parte CS EA/CH",
        "descripcion": "Resolución firme subcomisión no procede parte CS EA/CH",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "684": {
        "nombre": "Resolución firme subcomisión acepta factura CS EA/CH..." if len("Resolución firme subcomisión acepta factura CS EA/CH") > 60 else "Resolución firme subcomisión acepta factura CS EA/CH",
        "descripcion": "Resolución firme subcomisión acepta factura CS EA/CH",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "685": {
        "nombre": "Resolución firme subcomisión no procede factura CS EA/CH..." if len("Resolución firme subcomisión no procede factura CS EA/CH") > 60 else "Resolución firme subcomisión no procede factura CS EA/CH",
        "descripcion": "Resolución firme subcomisión no procede factura CS EA/CH",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "686": {
        "nombre": "Interlocutores por paciente alta especialización EA/CH EA/CH..." if len("Interlocutores por paciente alta especialización EA/CH EA/CH") > 60 else "Interlocutores por paciente alta especialización EA/CH EA/CH",
        "descripcion": "Interlocutores por paciente alta especialización EA/CH EA/CH",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "687": {
        "nombre": "Fin gestión lesionado alta complejidad en CAS. Gestionar con..." if len("Fin gestión lesionado alta complejidad en CAS. Gestionar con") > 60 else "Fin gestión lesionado alta complejidad en CAS. Gestionar con",
        "descripcion": "Fin gestión lesionado alta complejidad en CAS. Gestionar con",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "690": {
        "nombre": "Recurre resolución subcomisión factura..." if len("Recurre resolución subcomisión factura") > 60 else "Recurre resolución subcomisión factura",
        "descripcion": "Recurre resolución subcomisión factura",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "691": {
        "nombre": "Recurre resolución subcomisión factura..." if len("Recurre resolución subcomisión factura") > 60 else "Recurre resolución subcomisión factura",
        "descripcion": "Recurre resolución subcomisión factura",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "701": {
        "nombre": "Envío fuera de plazo (15 días naturales) del parte de urgenc..." if len("Envío fuera de plazo (15 días naturales) del parte de urgencia CS CH / EA") > 60 else "Envío fuera de plazo (15 días naturales) del parte de urgencia CS CH / EA",
        "descripcion": "Envío fuera de plazo (15 días naturales) del parte de urgencia CS CH / EA",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "702": {
        "nombre": "Envío fuera de plazo (15 días naturales) del parte de primer..." if len("Envío fuera de plazo (15 días naturales) del parte de primera") > 60 else "Envío fuera de plazo (15 días naturales) del parte de primera",
        "descripcion": "Envío fuera de plazo (15 días naturales) del parte de primera",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "703": {
        "nombre": "Envío fuera de plazo (15 días naturales) del informe de evol..." if len("Envío fuera de plazo (15 días naturales) del informe de evolución CS CH / EA") > 60 else "Envío fuera de plazo (15 días naturales) del informe de evolución CS CH / EA",
        "descripcion": "Envío fuera de plazo (15 días naturales) del informe de evolución CS CH / EA",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "704": {
        "nombre": "Comunicación fuera de plazo (15 días naturales) del cambio d..." if len("Comunicación fuera de plazo (15 días naturales) del cambio de") > 60 else "Comunicación fuera de plazo (15 días naturales) del cambio de",
        "descripcion": "Comunicación fuera de plazo (15 días naturales) del cambio de",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "705": {
        "nombre": "Presentación de las facturas de las asistencias prestadas po..." if len("Presentación de las facturas de las asistencias prestadas por los") > 60 else "Presentación de las facturas de las asistencias prestadas por los",
        "descripcion": "Presentación de las facturas de las asistencias prestadas por los",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "715": {
        "nombre": "Aviso caducidad factura. CS EA..." if len("Aviso caducidad factura. CS EA") > 60 else "Aviso caducidad factura. CS EA",
        "descripcion": "Aviso caducidad factura. CS EA",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "716": {
        "nombre": "Aviso envío fuera de plazo (15 días naturales) del informe d..." if len("Aviso envío fuera de plazo (15 días naturales) del informe de") > 60 else "Aviso envío fuera de plazo (15 días naturales) del informe de",
        "descripcion": "Aviso envío fuera de plazo (15 días naturales) del informe de",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "717": {
        "nombre": "Aviso presentación de las facturas de las asistencias presta..." if len("Aviso presentación de las facturas de las asistencias prestadas por") > 60 else "Aviso presentación de las facturas de las asistencias prestadas por",
        "descripcion": "Aviso presentación de las facturas de las asistencias prestadas por",
        "emisor": "DESCONOCIDO",
        "tipo": "PAGO",
    },
    "801": {
        "nombre": "Solicitud de autorización para calificación de lesionado alt..." if len("Solicitud de autorización para calificación de lesionado alta") > 60 else "Solicitud de autorización para calificación de lesionado alta",
        "descripcion": "Solicitud de autorización para calificación de lesionado alta",
        "emisor": "DESCONOCIDO",
        "tipo": "RECLAMACION",
    },
    "806": {
        "nombre": "Informe cambio diagnóstico CH EA..." if len("Informe cambio diagnóstico CH EA") > 60 else "Informe cambio diagnóstico CH EA",
        "descripcion": "Informe cambio diagnóstico CH EA",
        "emisor": "DESCONOCIDO",
        "tipo": "RECLAMACION",
    },
    "811": {
        "nombre": "Informe médico de evolución CH EA..." if len("Informe médico de evolución CH EA") > 60 else "Informe médico de evolución CH EA",
        "descripcion": "Informe médico de evolución CH EA",
        "emisor": "DESCONOCIDO",
        "tipo": "RECLAMACION",
    },
    "814": {
        "nombre": "Envía documento hoja de firmas CH EA..." if len("Envía documento hoja de firmas CH EA") > 60 else "Envía documento hoja de firmas CH EA",
        "descripcion": "Envía documento hoja de firmas CH EA",
        "emisor": "DESCONOCIDO",
        "tipo": "RECLAMACION",
    },
    "821": {
        "nombre": "Envío declaración de responsable CH CCS..." if len("Envío declaración de responsable CH CCS") > 60 else "Envío declaración de responsable CH CCS",
        "descripcion": "Envío declaración de responsable CH CCS",
        "emisor": "DESCONOCIDO",
        "tipo": "RECLAMACION",
    },
    "822": {
        "nombre": "Envío nueva declaración responsable CH CCS..." if len("Envío nueva declaración responsable CH CCS") > 60 else "Envío nueva declaración responsable CH CCS",
        "descripcion": "Envío nueva declaración responsable CH CCS",
        "emisor": "DESCONOCIDO",
        "tipo": "RECLAMACION",
    },
    "823": {
        "nombre": "Autorización Infiltraciones-bloqueos facetarios, nerviosos. ..." if len("Autorización Infiltraciones-bloqueos facetarios, nerviosos. CH EA") > 60 else "Autorización Infiltraciones-bloqueos facetarios, nerviosos. CH EA",
        "descripcion": "Autorización Infiltraciones-bloqueos facetarios, nerviosos. CH EA",
        "emisor": "DESCONOCIDO",
        "tipo": "RECLAMACION",
    },
    "824": {
        "nombre": "Autorización ondas de choque radiales. CH EA..." if len("Autorización ondas de choque radiales. CH EA") > 60 else "Autorización ondas de choque radiales. CH EA",
        "descripcion": "Autorización ondas de choque radiales. CH EA",
        "emisor": "DESCONOCIDO",
        "tipo": "RECLAMACION",
    },
    "825": {
        "nombre": "Autorización ondas de choque focales. CH EA..." if len("Autorización ondas de choque focales. CH EA") > 60 else "Autorización ondas de choque focales. CH EA",
        "descripcion": "Autorización ondas de choque focales. CH EA",
        "emisor": "DESCONOCIDO",
        "tipo": "RECLAMACION",
    },
    "841": {
        "nombre": "Justificante de rechazo de parte EA CH..." if len("Justificante de rechazo de parte EA CH") > 60 else "Justificante de rechazo de parte EA CH",
        "descripcion": "Justificante de rechazo de parte EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "RECLAMACION",
    },
    "861": {
        "nombre": "EA justifica aplicar módulo reducido EA CH..." if len("EA justifica aplicar módulo reducido EA CH") > 60 else "EA justifica aplicar módulo reducido EA CH",
        "descripcion": "EA justifica aplicar módulo reducido EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "RECLAMACION",
    },
    "863": {
        "nombre": "Envía Documentos originales información aclaratoria. CH EA..." if len("Envía Documentos originales información aclaratoria. CH EA") > 60 else "Envía Documentos originales información aclaratoria. CH EA",
        "descripcion": "Envía Documentos originales información aclaratoria. CH EA",
        "emisor": "DESCONOCIDO",
        "tipo": "RECLAMACION",
    },
    "864": {
        "nombre": "Centro sanitario justifica diálogo aplicación módulo reducid..." if len("Centro sanitario justifica diálogo aplicación módulo reducido CH EA") > 60 else "Centro sanitario justifica diálogo aplicación módulo reducido CH EA",
        "descripcion": "Centro sanitario justifica diálogo aplicación módulo reducido CH EA",
        "emisor": "DESCONOCIDO",
        "tipo": "RECLAMACION",
    },
    "865": {
        "nombre": "Documento original de justificación de envío fuera de plazo...." if len("Documento original de justificación de envío fuera de plazo. CH EA") > 60 else "Documento original de justificación de envío fuera de plazo. CH EA",
        "descripcion": "Documento original de justificación de envío fuera de plazo. CH EA",
        "emisor": "DESCONOCIDO",
        "tipo": "RECLAMACION",
    },
    "866": {
        "nombre": "Documentación original sin catalogar. CH EA..." if len("Documentación original sin catalogar. CH EA") > 60 else "Documentación original sin catalogar. CH EA",
        "descripcion": "Documentación original sin catalogar. CH EA",
        "emisor": "DESCONOCIDO",
        "tipo": "RECLAMACION",
    },
    "867": {
        "nombre": "Documentación original sin catalogar. EA CH..." if len("Documentación original sin catalogar. EA CH") > 60 else "Documentación original sin catalogar. EA CH",
        "descripcion": "Documentación original sin catalogar. EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "RECLAMACION",
    },
    "869": {
        "nombre": "Envía Documentos originales de aclaración factura CH EA..." if len("Envía Documentos originales de aclaración factura CH EA") > 60 else "Envía Documentos originales de aclaración factura CH EA",
        "descripcion": "Envía Documentos originales de aclaración factura CH EA",
        "emisor": "DESCONOCIDO",
        "tipo": "RECLAMACION",
    },
    "870": {
        "nombre": "Documento justificante rechazo factura EA CH..." if len("Documento justificante rechazo factura EA CH") > 60 else "Documento justificante rechazo factura EA CH",
        "descripcion": "Documento justificante rechazo factura EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "RECLAMACION",
    },
    "874": {
        "nombre": "Documento original de justificante de no aseguramiento. EA C..." if len("Documento original de justificante de no aseguramiento. EA CH") > 60 else "Documento original de justificante de no aseguramiento. EA CH",
        "descripcion": "Documento original de justificante de no aseguramiento. EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "RECLAMACION",
    },
    "876": {
        "nombre": "Envía doc. original aclaración declaración responsable CH CC..." if len("Envía doc. original aclaración declaración responsable CH CCS") > 60 else "Envía doc. original aclaración declaración responsable CH CCS",
        "descripcion": "Envía doc. original aclaración declaración responsable CH CCS",
        "emisor": "DESCONOCIDO",
        "tipo": "RECLAMACION",
    },
    "877": {
        "nombre": "Doc. original información alegaciones parte CH EA..." if len("Doc. original información alegaciones parte CH EA") > 60 else "Doc. original información alegaciones parte CH EA",
        "descripcion": "Doc. original información alegaciones parte CH EA",
        "emisor": "DESCONOCIDO",
        "tipo": "RECLAMACION",
    },
    "878": {
        "nombre": "Doc. original información alegaciones parte EA CH..." if len("Doc. original información alegaciones parte EA CH") > 60 else "Doc. original información alegaciones parte EA CH",
        "descripcion": "Doc. original información alegaciones parte EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "RECLAMACION",
    },
    "879": {
        "nombre": "Doc. original información alegaciones factura CH EA..." if len("Doc. original información alegaciones factura CH EA") > 60 else "Doc. original información alegaciones factura CH EA",
        "descripcion": "Doc. original información alegaciones factura CH EA",
        "emisor": "DESCONOCIDO",
        "tipo": "RECLAMACION",
    },
    "880": {
        "nombre": "Doc. original información alegaciones factura EA CH..." if len("Doc. original información alegaciones factura EA CH") > 60 else "Doc. original información alegaciones factura EA CH",
        "descripcion": "Doc. original información alegaciones factura EA CH",
        "emisor": "DESCONOCIDO",
        "tipo": "RECLAMACION",
    },
    "881": {
        "nombre": "Informe de alta de urgencias CH EA..." if len("Informe de alta de urgencias CH EA") > 60 else "Informe de alta de urgencias CH EA",
        "descripcion": "Informe de alta de urgencias CH EA",
        "emisor": "DESCONOCIDO",
        "tipo": "RECLAMACION",
    },
    "885": {
        "nombre": "Envío informe de alta CH EA..." if len("Envío informe de alta CH EA") > 60 else "Envío informe de alta CH EA",
        "descripcion": "Envío informe de alta CH EA",
        "emisor": "DESCONOCIDO",
        "tipo": "RECLAMACION",
    },
    "890": {
        "nombre": "EA envía doc. aclaraciones Parte Asistencia, solicitud subco..." if len("EA envía doc. aclaraciones Parte Asistencia, solicitud subcomisión EA CS") > 60 else "EA envía doc. aclaraciones Parte Asistencia, solicitud subcomisión EA CS",
        "descripcion": "EA envía doc. aclaraciones Parte Asistencia, solicitud subcomisión EA CS",
        "emisor": "DESCONOCIDO",
        "tipo": "RECLAMACION",
    },
    "891": {
        "nombre": "CH envía doc aclaraciones Parte Asistencia, solicitud subcom..." if len("CH envía doc aclaraciones Parte Asistencia, solicitud subcomisión CH CS") > 60 else "CH envía doc aclaraciones Parte Asistencia, solicitud subcomisión CH CS",
        "descripcion": "CH envía doc aclaraciones Parte Asistencia, solicitud subcomisión CH CS",
        "emisor": "DESCONOCIDO",
        "tipo": "RECLAMACION",
    },
    "892": {
        "nombre": "CH envía doc. aclaraciones Parte Asistencia, solicitud Comis..." if len("CH envía doc. aclaraciones Parte Asistencia, solicitud Comisión CH CS") > 60 else "CH envía doc. aclaraciones Parte Asistencia, solicitud Comisión CH CS",
        "descripcion": "CH envía doc. aclaraciones Parte Asistencia, solicitud Comisión CH CS",
        "emisor": "DESCONOCIDO",
        "tipo": "RECLAMACION",
    },
    "893": {
        "nombre": "Envía documentación solicitud subcomisión Factura (adicional..." if len("Envía documentación solicitud subcomisión Factura (adicional)") > 60 else "Envía documentación solicitud subcomisión Factura (adicional)",
        "descripcion": "Envía documentación solicitud subcomisión Factura (adicional)",
        "emisor": "DESCONOCIDO",
        "tipo": "RECLAMACION",
    },
    "894": {
        "nombre": "EA envía doc. aclaraciones Factura, solicitud Comisión EA CS..." if len("EA envía doc. aclaraciones Factura, solicitud Comisión EA CS") > 60 else "EA envía doc. aclaraciones Factura, solicitud Comisión EA CS",
        "descripcion": "EA envía doc. aclaraciones Factura, solicitud Comisión EA CS",
        "emisor": "DESCONOCIDO",
        "tipo": "RECLAMACION",
    },
    "895": {
        "nombre": "CH envía doc. aclaraciones Factura, solicitud Comisión CH CS..." if len("CH envía doc. aclaraciones Factura, solicitud Comisión CH CS") > 60 else "CH envía doc. aclaraciones Factura, solicitud Comisión CH CS",
        "descripcion": "CH envía doc. aclaraciones Factura, solicitud Comisión CH CS",
        "emisor": "DESCONOCIDO",
        "tipo": "RECLAMACION",
    },
    "896": {
        "nombre": "Documentación subcomisión/comisión CS EA/CH..." if len("Documentación subcomisión/comisión CS EA/CH") > 60 else "Documentación subcomisión/comisión CS EA/CH",
        "descripcion": "Documentación subcomisión/comisión CS EA/CH",
        "emisor": "DESCONOCIDO",
        "tipo": "RECLAMACION",
    },
    "897": {
        "nombre": "Documentación adicional tras petición subcomisión/comisión C..." if len("Documentación adicional tras petición subcomisión/comisión CS EA/CH") > 60 else "Documentación adicional tras petición subcomisión/comisión CS EA/CH",
        "descripcion": "Documentación adicional tras petición subcomisión/comisión CS EA/CH",
        "emisor": "DESCONOCIDO",
        "tipo": "RECLAMACION",
    },
    "898": {
        "nombre": "EA envía doc. aclaraciones Parte Asistencia, solicitud Comis..." if len("EA envía doc. aclaraciones Parte Asistencia, solicitud Comisión EA CS") > 60 else "EA envía doc. aclaraciones Parte Asistencia, solicitud Comisión EA CS",
        "descripcion": "EA envía doc. aclaraciones Parte Asistencia, solicitud Comisión EA CS",
        "emisor": "DESCONOCIDO",
        "tipo": "RECLAMACION",
    },
    "899": {
        "nombre": "Envía documentación solicitud subcomisión Factura (adicional..." if len("Envía documentación solicitud subcomisión Factura (adicional) (sólo") > 60 else "Envía documentación solicitud subcomisión Factura (adicional) (sólo",
        "descripcion": "Envía documentación solicitud subcomisión Factura (adicional) (sólo",
        "emisor": "DESCONOCIDO",
        "tipo": "RECLAMACION",
    },
}